package c_CoolText__Serif_Italic

import "strings"

const Name = "Serif Italic"
const NameSanitized = "Serif_Italic"
const NameLoweredSanitized = "serif_italic"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","0",-1)
	strO = strings.Replace(strO,"1","1",-1)
	strO = strings.Replace(strO,"2","2",-1)
	strO = strings.Replace(strO,"3","3",-1)
	strO = strings.Replace(strO,"4","4",-1)
	strO = strings.Replace(strO,"5","5",-1)
	strO = strings.Replace(strO,"6","6",-1)
	strO = strings.Replace(strO,"7","7",-1)
	strO = strings.Replace(strO,"8","8",-1)
	strO = strings.Replace(strO,"9","9",-1)
	strO = strings.Replace(strO,"A","𝐴",-1)
	strO = strings.Replace(strO,"B","𝐵",-1)
	strO = strings.Replace(strO,"C","𝐶",-1)
	strO = strings.Replace(strO,"D","𝐷",-1)
	strO = strings.Replace(strO,"E","𝐸",-1)
	strO = strings.Replace(strO,"F","𝐹",-1)
	strO = strings.Replace(strO,"G","𝐺",-1)
	strO = strings.Replace(strO,"H","𝐻",-1)
	strO = strings.Replace(strO,"I","𝐼",-1)
	strO = strings.Replace(strO,"J","𝐽",-1)
	strO = strings.Replace(strO,"K","𝐾",-1)
	strO = strings.Replace(strO,"L","𝐿",-1)
	strO = strings.Replace(strO,"M","𝑀",-1)
	strO = strings.Replace(strO,"N","𝑁",-1)
	strO = strings.Replace(strO,"O","𝑂",-1)
	strO = strings.Replace(strO,"P","𝑃",-1)
	strO = strings.Replace(strO,"Q","𝑄",-1)
	strO = strings.Replace(strO,"R","𝑅",-1)
	strO = strings.Replace(strO,"S","𝑆",-1)
	strO = strings.Replace(strO,"T","𝑇",-1)
	strO = strings.Replace(strO,"U","𝑈",-1)
	strO = strings.Replace(strO,"V","𝑉",-1)
	strO = strings.Replace(strO,"W","𝑊",-1)
	strO = strings.Replace(strO,"X","𝑋",-1)
	strO = strings.Replace(strO,"Y","𝑌",-1)
	strO = strings.Replace(strO,"Z","𝑍",-1)
	strO = strings.Replace(strO,"a","𝑎",-1)
	strO = strings.Replace(strO,"b","𝑏",-1)
	strO = strings.Replace(strO,"c","𝑐",-1)
	strO = strings.Replace(strO,"d","𝑑",-1)
	strO = strings.Replace(strO,"e","𝑒",-1)
	strO = strings.Replace(strO,"f","𝑓",-1)
	strO = strings.Replace(strO,"g","𝑔",-1)
	strO = strings.Replace(strO,"h","ℎ",-1)
	strO = strings.Replace(strO,"i","𝑖",-1)
	strO = strings.Replace(strO,"j","𝑗",-1)
	strO = strings.Replace(strO,"k","𝑘",-1)
	strO = strings.Replace(strO,"l","𝑙",-1)
	strO = strings.Replace(strO,"m","𝑚",-1)
	strO = strings.Replace(strO,"n","𝑛",-1)
	strO = strings.Replace(strO,"o","𝑜",-1)
	strO = strings.Replace(strO,"p","𝑝",-1)
	strO = strings.Replace(strO,"q","𝑞",-1)
	strO = strings.Replace(strO,"r","𝑟",-1)
	strO = strings.Replace(strO,"s","𝑠",-1)
	strO = strings.Replace(strO,"t","𝑡",-1)
	strO = strings.Replace(strO,"u","𝑢",-1)
	strO = strings.Replace(strO,"v","𝑣",-1)
	strO = strings.Replace(strO,"w","𝑤",-1)
	strO = strings.Replace(strO,"x","𝑥",-1)
	strO = strings.Replace(strO,"y","𝑦",-1)
	strO = strings.Replace(strO,"z","𝑧",-1)
	return strO
}