package c_CoolText__Slicer

import "strings"

const Name = "Slicer"
const NameSanitized = "Slicer"
const NameLoweredSanitized = "slicer"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","0",-1)
	strO = strings.Replace(strO,"1","1",-1)
	strO = strings.Replace(strO,"2","ƻ",-1)
	strO = strings.Replace(strO,"3","3",-1)
	strO = strings.Replace(strO,"4","4",-1)
	strO = strings.Replace(strO,"5","5",-1)
	strO = strings.Replace(strO,"6","6",-1)
	strO = strings.Replace(strO,"7","7",-1)
	strO = strings.Replace(strO,"8","8",-1)
	strO = strings.Replace(strO,"9","9",-1)
	strO = strings.Replace(strO,"A","Ⱥ",-1)
	strO = strings.Replace(strO,"B","Ƀ",-1)
	strO = strings.Replace(strO,"C","Ȼ",-1)
	strO = strings.Replace(strO,"D","Đ",-1)
	strO = strings.Replace(strO,"E","Ɇ",-1)
	strO = strings.Replace(strO,"F","F",-1)
	strO = strings.Replace(strO,"G","Ǥ",-1)
	strO = strings.Replace(strO,"H","Ħ",-1)
	strO = strings.Replace(strO,"I","Ɨ",-1)
	strO = strings.Replace(strO,"J","Ɉ",-1)
	strO = strings.Replace(strO,"K","Ꝁ",-1)
	strO = strings.Replace(strO,"L","Ł",-1)
	strO = strings.Replace(strO,"M","M",-1)
	strO = strings.Replace(strO,"N","N",-1)
	strO = strings.Replace(strO,"O","Ø",-1)
	strO = strings.Replace(strO,"P","Ᵽ",-1)
	strO = strings.Replace(strO,"Q","Ꝗ",-1)
	strO = strings.Replace(strO,"R","Ɍ",-1)
	strO = strings.Replace(strO,"S","S",-1)
	strO = strings.Replace(strO,"T","Ŧ",-1)
	strO = strings.Replace(strO,"U","ᵾ",-1)
	strO = strings.Replace(strO,"V","V",-1)
	strO = strings.Replace(strO,"W","W",-1)
	strO = strings.Replace(strO,"X","X",-1)
	strO = strings.Replace(strO,"Y","Ɏ",-1)
	strO = strings.Replace(strO,"Z","Ƶ",-1)
	strO = strings.Replace(strO,"a","Ⱥ",-1)
	strO = strings.Replace(strO,"b","ƀ",-1)
	strO = strings.Replace(strO,"c","ȼ",-1)
	strO = strings.Replace(strO,"d","đ",-1)
	strO = strings.Replace(strO,"e","ɇ",-1)
	strO = strings.Replace(strO,"f","f",-1)
	strO = strings.Replace(strO,"g","ǥ",-1)
	strO = strings.Replace(strO,"h","ħ",-1)
	strO = strings.Replace(strO,"i","ɨ",-1)
	strO = strings.Replace(strO,"j","ɉ",-1)
	strO = strings.Replace(strO,"k","ꝁ",-1)
	strO = strings.Replace(strO,"l","ł",-1)
	strO = strings.Replace(strO,"m","m",-1)
	strO = strings.Replace(strO,"n","n",-1)
	strO = strings.Replace(strO,"o","ø",-1)
	strO = strings.Replace(strO,"p","ᵽ",-1)
	strO = strings.Replace(strO,"q","ꝗ",-1)
	strO = strings.Replace(strO,"r","ɍ",-1)
	strO = strings.Replace(strO,"s","s",-1)
	strO = strings.Replace(strO,"t","ŧ",-1)
	strO = strings.Replace(strO,"u","ᵾ",-1)
	strO = strings.Replace(strO,"v","v",-1)
	strO = strings.Replace(strO,"w","w",-1)
	strO = strings.Replace(strO,"x","x",-1)
	strO = strings.Replace(strO,"y","ɏ",-1)
	strO = strings.Replace(strO,"z","ƶ",-1)
	return strO
}