package c_CoolText__Notebook

import "strings"

const Name = "Notebook"
const NameSanitized = "Notebook"
const NameLoweredSanitized = "notebook"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","0",-1)
	strO = strings.Replace(strO,"1","1",-1)
	strO = strings.Replace(strO,"2","2",-1)
	strO = strings.Replace(strO,"3","3",-1)
	strO = strings.Replace(strO,"4","4",-1)
	strO = strings.Replace(strO,"5","5",-1)
	strO = strings.Replace(strO,"6","6",-1)
	strO = strings.Replace(strO,"7","7",-1)
	strO = strings.Replace(strO,"8","8",-1)
	strO = strings.Replace(strO,"9","9",-1)
	strO = strings.Replace(strO,"A","ᗩ",-1)
	strO = strings.Replace(strO,"B","ᗷ",-1)
	strO = strings.Replace(strO,"C","ᑕ",-1)
	strO = strings.Replace(strO,"D","ᗪ",-1)
	strO = strings.Replace(strO,"E","E",-1)
	strO = strings.Replace(strO,"F","ᖴ",-1)
	strO = strings.Replace(strO,"G","G",-1)
	strO = strings.Replace(strO,"H","ᕼ",-1)
	strO = strings.Replace(strO,"I","I",-1)
	strO = strings.Replace(strO,"J","ᒍ",-1)
	strO = strings.Replace(strO,"K","K",-1)
	strO = strings.Replace(strO,"L","ᒪ",-1)
	strO = strings.Replace(strO,"M","ᗰ",-1)
	strO = strings.Replace(strO,"N","ᑎ",-1)
	strO = strings.Replace(strO,"O","O",-1)
	strO = strings.Replace(strO,"P","ᑭ",-1)
	strO = strings.Replace(strO,"Q","ᑫ",-1)
	strO = strings.Replace(strO,"R","ᖇ",-1)
	strO = strings.Replace(strO,"S","ᔕ",-1)
	strO = strings.Replace(strO,"T","T",-1)
	strO = strings.Replace(strO,"U","ᑌ",-1)
	strO = strings.Replace(strO,"V","ᐯ",-1)
	strO = strings.Replace(strO,"W","ᗯ",-1)
	strO = strings.Replace(strO,"X","᙭",-1)
	strO = strings.Replace(strO,"Y","Y",-1)
	strO = strings.Replace(strO,"Z","ᘔ",-1)
	strO = strings.Replace(strO,"a","ᗩ",-1)
	strO = strings.Replace(strO,"b","ᗷ",-1)
	strO = strings.Replace(strO,"c","ᑕ",-1)
	strO = strings.Replace(strO,"d","ᗪ",-1)
	strO = strings.Replace(strO,"e","E",-1)
	strO = strings.Replace(strO,"f","ᖴ",-1)
	strO = strings.Replace(strO,"g","G",-1)
	strO = strings.Replace(strO,"h","ᕼ",-1)
	strO = strings.Replace(strO,"i","I",-1)
	strO = strings.Replace(strO,"j","ᒍ",-1)
	strO = strings.Replace(strO,"k","K",-1)
	strO = strings.Replace(strO,"l","ᒪ",-1)
	strO = strings.Replace(strO,"m","ᗰ",-1)
	strO = strings.Replace(strO,"n","ᑎ",-1)
	strO = strings.Replace(strO,"o","O",-1)
	strO = strings.Replace(strO,"p","ᑭ",-1)
	strO = strings.Replace(strO,"q","ᑫ",-1)
	strO = strings.Replace(strO,"r","ᖇ",-1)
	strO = strings.Replace(strO,"s","ᔕ",-1)
	strO = strings.Replace(strO,"t","T",-1)
	strO = strings.Replace(strO,"u","ᑌ",-1)
	strO = strings.Replace(strO,"v","ᐯ",-1)
	strO = strings.Replace(strO,"w","ᗯ",-1)
	strO = strings.Replace(strO,"x","᙭",-1)
	strO = strings.Replace(strO,"y","Y",-1)
	strO = strings.Replace(strO,"z","ᘔ",-1)
	return strO
}