package c_CoolText__All_Caps

import "strings"

const Name = "All Caps"
const NameSanitized = "All_Caps"
const NameLoweredSanitized = "all_caps"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","𝟶",-1)
	strO = strings.Replace(strO,"1","𝟷",-1)
	strO = strings.Replace(strO,"2","𝟸",-1)
	strO = strings.Replace(strO,"3","𝟹",-1)
	strO = strings.Replace(strO,"4","𝟺",-1)
	strO = strings.Replace(strO,"5","𝟻",-1)
	strO = strings.Replace(strO,"6","𝟼",-1)
	strO = strings.Replace(strO,"7","𝟽",-1)
	strO = strings.Replace(strO,"8","𝟾",-1)
	strO = strings.Replace(strO,"9","𝟿",-1)
	strO = strings.Replace(strO,"A","ᴀ",-1)
	strO = strings.Replace(strO,"B","ʙ",-1)
	strO = strings.Replace(strO,"C","ᴄ",-1)
	strO = strings.Replace(strO,"D","ᴅ",-1)
	strO = strings.Replace(strO,"E","ᴇ",-1)
	strO = strings.Replace(strO,"F","ғ",-1)
	strO = strings.Replace(strO,"G","ɢ",-1)
	strO = strings.Replace(strO,"H","ʜ",-1)
	strO = strings.Replace(strO,"I","ɪ",-1)
	strO = strings.Replace(strO,"J","ᴊ",-1)
	strO = strings.Replace(strO,"K","ᴋ",-1)
	strO = strings.Replace(strO,"L","ʟ",-1)
	strO = strings.Replace(strO,"M","ᴍ",-1)
	strO = strings.Replace(strO,"N","ɴ",-1)
	strO = strings.Replace(strO,"O","ᴏ",-1)
	strO = strings.Replace(strO,"P","ᴘ",-1)
	strO = strings.Replace(strO,"Q","ǫ",-1)
	strO = strings.Replace(strO,"R","ʀ",-1)
	strO = strings.Replace(strO,"S","s",-1)
	strO = strings.Replace(strO,"T","ᴛ",-1)
	strO = strings.Replace(strO,"U","ᴜ",-1)
	strO = strings.Replace(strO,"V","ᴠ",-1)
	strO = strings.Replace(strO,"W","ᴡ",-1)
	strO = strings.Replace(strO,"X","x",-1)
	strO = strings.Replace(strO,"Y","ʏ",-1)
	strO = strings.Replace(strO,"Z","ᴢ",-1)
	strO = strings.Replace(strO,"a","ᴀ",-1)
	strO = strings.Replace(strO,"b","ʙ",-1)
	strO = strings.Replace(strO,"c","ᴄ",-1)
	strO = strings.Replace(strO,"d","ᴅ",-1)
	strO = strings.Replace(strO,"e","ᴇ",-1)
	strO = strings.Replace(strO,"f","ғ",-1)
	strO = strings.Replace(strO,"g","ɢ",-1)
	strO = strings.Replace(strO,"h","ʜ",-1)
	strO = strings.Replace(strO,"i","ɪ",-1)
	strO = strings.Replace(strO,"j","ᴊ",-1)
	strO = strings.Replace(strO,"k","ᴋ",-1)
	strO = strings.Replace(strO,"l","ʟ",-1)
	strO = strings.Replace(strO,"m","ᴍ",-1)
	strO = strings.Replace(strO,"n","ɴ",-1)
	strO = strings.Replace(strO,"o","ᴏ",-1)
	strO = strings.Replace(strO,"p","ᴘ",-1)
	strO = strings.Replace(strO,"q","ǫ",-1)
	strO = strings.Replace(strO,"r","ʀ",-1)
	strO = strings.Replace(strO,"s","s",-1)
	strO = strings.Replace(strO,"t","ᴛ",-1)
	strO = strings.Replace(strO,"u","ᴜ",-1)
	strO = strings.Replace(strO,"v","ᴠ",-1)
	strO = strings.Replace(strO,"w","ᴡ",-1)
	strO = strings.Replace(strO,"x","x",-1)
	strO = strings.Replace(strO,"y","ʏ",-1)
	strO = strings.Replace(strO,"z","ᴢ",-1)
	return strO
}