package c_CoolText__Gawd_Mode

import "strings"

const Name = "Gawd Mode"
const NameSanitized = "Gawd_Mode"
const NameLoweredSanitized = "gawd_mode"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","0",-1)
	strO = strings.Replace(strO,"1","1",-1)
	strO = strings.Replace(strO,"2","2",-1)
	strO = strings.Replace(strO,"3","3",-1)
	strO = strings.Replace(strO,"4","4",-1)
	strO = strings.Replace(strO,"5","5",-1)
	strO = strings.Replace(strO,"6","6",-1)
	strO = strings.Replace(strO,"7","7",-1)
	strO = strings.Replace(strO,"8","8",-1)
	strO = strings.Replace(strO,"9","9",-1)
	strO = strings.Replace(strO,"A","ƛ",-1)
	strO = strings.Replace(strO,"B","Ɓ",-1)
	strO = strings.Replace(strO,"C","Ƈ",-1)
	strO = strings.Replace(strO,"D","Ɗ",-1)
	strO = strings.Replace(strO,"E","Є",-1)
	strO = strings.Replace(strO,"F","Ƒ",-1)
	strO = strings.Replace(strO,"G","Ɠ",-1)
	strO = strings.Replace(strO,"H","Ӈ",-1)
	strO = strings.Replace(strO,"I","Ɩ",-1)
	strO = strings.Replace(strO,"J","ʆ",-1)
	strO = strings.Replace(strO,"K","Ƙ",-1)
	strO = strings.Replace(strO,"L","Լ",-1)
	strO = strings.Replace(strO,"M","M",-1)
	strO = strings.Replace(strO,"N","Ɲ",-1)
	strO = strings.Replace(strO,"O","Ơ",-1)
	strO = strings.Replace(strO,"P","Ƥ",-1)
	strO = strings.Replace(strO,"Q","Ƣ",-1)
	strO = strings.Replace(strO,"R","Ʀ",-1)
	strO = strings.Replace(strO,"S","Ƨ",-1)
	strO = strings.Replace(strO,"T","Ƭ",-1)
	strO = strings.Replace(strO,"U","Ʋ",-1)
	strO = strings.Replace(strO,"V","Ɣ",-1)
	strO = strings.Replace(strO,"W","Ɯ",-1)
	strO = strings.Replace(strO,"X","Ҳ",-1)
	strO = strings.Replace(strO,"Y","Ƴ",-1)
	strO = strings.Replace(strO,"Z","Ȥ",-1)
	strO = strings.Replace(strO,"a","ƛ",-1)
	strO = strings.Replace(strO,"b","Ɓ",-1)
	strO = strings.Replace(strO,"c","Ƈ",-1)
	strO = strings.Replace(strO,"d","Ɗ",-1)
	strO = strings.Replace(strO,"e","Є",-1)
	strO = strings.Replace(strO,"f","Ƒ",-1)
	strO = strings.Replace(strO,"g","Ɠ",-1)
	strO = strings.Replace(strO,"h","Ӈ",-1)
	strO = strings.Replace(strO,"i","Ɩ",-1)
	strO = strings.Replace(strO,"j","ʆ",-1)
	strO = strings.Replace(strO,"k","Ƙ",-1)
	strO = strings.Replace(strO,"l","Լ",-1)
	strO = strings.Replace(strO,"m","M",-1)
	strO = strings.Replace(strO,"n","Ɲ",-1)
	strO = strings.Replace(strO,"o","Ơ",-1)
	strO = strings.Replace(strO,"p","Ƥ",-1)
	strO = strings.Replace(strO,"q","Ƣ",-1)
	strO = strings.Replace(strO,"r","Ʀ",-1)
	strO = strings.Replace(strO,"s","Ƨ",-1)
	strO = strings.Replace(strO,"t","Ƭ",-1)
	strO = strings.Replace(strO,"u","Ʋ",-1)
	strO = strings.Replace(strO,"v","Ɣ",-1)
	strO = strings.Replace(strO,"w","Ɯ",-1)
	strO = strings.Replace(strO,"x","Ҳ",-1)
	strO = strings.Replace(strO,"y","Ƴ",-1)
	strO = strings.Replace(strO,"z","Ȥ",-1)
	return strO
}