package c_CoolText__Impression

import "strings"

const Name = "Impression"
const NameSanitized = "Impression"
const NameLoweredSanitized = "impression"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","0",-1)
	strO = strings.Replace(strO,"1","1",-1)
	strO = strings.Replace(strO,"2","2",-1)
	strO = strings.Replace(strO,"3","3",-1)
	strO = strings.Replace(strO,"4","4",-1)
	strO = strings.Replace(strO,"5","5",-1)
	strO = strings.Replace(strO,"6","6",-1)
	strO = strings.Replace(strO,"7","7",-1)
	strO = strings.Replace(strO,"8","8",-1)
	strO = strings.Replace(strO,"9","9",-1)
	strO = strings.Replace(strO,"A","A",-1)
	strO = strings.Replace(strO,"B","B",-1)
	strO = strings.Replace(strO,"C","C",-1)
	strO = strings.Replace(strO,"D","D",-1)
	strO = strings.Replace(strO,"E","E",-1)
	strO = strings.Replace(strO,"F","F",-1)
	strO = strings.Replace(strO,"G","G",-1)
	strO = strings.Replace(strO,"H","H",-1)
	strO = strings.Replace(strO,"I","I",-1)
	strO = strings.Replace(strO,"J","J",-1)
	strO = strings.Replace(strO,"K","K",-1)
	strO = strings.Replace(strO,"L","L",-1)
	strO = strings.Replace(strO,"M","M",-1)
	strO = strings.Replace(strO,"N","N",-1)
	strO = strings.Replace(strO,"O","O",-1)
	strO = strings.Replace(strO,"P","P",-1)
	strO = strings.Replace(strO,"Q","Q",-1)
	strO = strings.Replace(strO,"R","R",-1)
	strO = strings.Replace(strO,"S","S",-1)
	strO = strings.Replace(strO,"T","T",-1)
	strO = strings.Replace(strO,"U","U",-1)
	strO = strings.Replace(strO,"V","V",-1)
	strO = strings.Replace(strO,"W","W",-1)
	strO = strings.Replace(strO,"X","X",-1)
	strO = strings.Replace(strO,"Y","Y",-1)
	strO = strings.Replace(strO,"Z","Z",-1)
	strO = strings.Replace(strO,"a","ã",-1)
	strO = strings.Replace(strO,"b","b",-1)
	strO = strings.Replace(strO,"c","ĉ",-1)
	strO = strings.Replace(strO,"d","d",-1)
	strO = strings.Replace(strO,"e","ê",-1)
	strO = strings.Replace(strO,"f","f",-1)
	strO = strings.Replace(strO,"g","ĝ",-1)
	strO = strings.Replace(strO,"h","ĥ",-1)
	strO = strings.Replace(strO,"i","ĩ",-1)
	strO = strings.Replace(strO,"j","ĵ",-1)
	strO = strings.Replace(strO,"k","k",-1)
	strO = strings.Replace(strO,"l","l",-1)
	strO = strings.Replace(strO,"m","m",-1)
	strO = strings.Replace(strO,"n","ñ",-1)
	strO = strings.Replace(strO,"o","ǿ",-1)
	strO = strings.Replace(strO,"p","p",-1)
	strO = strings.Replace(strO,"q","q",-1)
	strO = strings.Replace(strO,"r","ѓ",-1)
	strO = strings.Replace(strO,"s","ş",-1)
	strO = strings.Replace(strO,"t","ţ",-1)
	strO = strings.Replace(strO,"u","ʉ",-1)
	strO = strings.Replace(strO,"v","v",-1)
	strO = strings.Replace(strO,"w","ŵ",-1)
	strO = strings.Replace(strO,"x","x",-1)
	strO = strings.Replace(strO,"y","ŷ",-1)
	strO = strings.Replace(strO,"z","ż",-1)
	return strO
}