package c_CoolText__Bold_Italic

import "strings"

const Name = "Bold Italic"
const NameSanitized = "Bold_Italic"
const NameLoweredSanitized = "bold_italic"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","0",-1)
	strO = strings.Replace(strO,"1","1",-1)
	strO = strings.Replace(strO,"2","2",-1)
	strO = strings.Replace(strO,"3","3",-1)
	strO = strings.Replace(strO,"4","4",-1)
	strO = strings.Replace(strO,"5","5",-1)
	strO = strings.Replace(strO,"6","6",-1)
	strO = strings.Replace(strO,"7","7",-1)
	strO = strings.Replace(strO,"8","8",-1)
	strO = strings.Replace(strO,"9","9",-1)
	strO = strings.Replace(strO,"A","𝘼",-1)
	strO = strings.Replace(strO,"B","𝘽",-1)
	strO = strings.Replace(strO,"C","𝘾",-1)
	strO = strings.Replace(strO,"D","𝘿",-1)
	strO = strings.Replace(strO,"E","𝙀",-1)
	strO = strings.Replace(strO,"F","𝙁",-1)
	strO = strings.Replace(strO,"G","𝙂",-1)
	strO = strings.Replace(strO,"H","𝙃",-1)
	strO = strings.Replace(strO,"I","𝙄",-1)
	strO = strings.Replace(strO,"J","𝙅",-1)
	strO = strings.Replace(strO,"K","𝙆",-1)
	strO = strings.Replace(strO,"L","𝙇",-1)
	strO = strings.Replace(strO,"M","𝙈",-1)
	strO = strings.Replace(strO,"N","𝙉",-1)
	strO = strings.Replace(strO,"O","𝙊",-1)
	strO = strings.Replace(strO,"P","𝙋",-1)
	strO = strings.Replace(strO,"Q","𝙌",-1)
	strO = strings.Replace(strO,"R","𝙍",-1)
	strO = strings.Replace(strO,"S","𝙎",-1)
	strO = strings.Replace(strO,"T","𝙏",-1)
	strO = strings.Replace(strO,"U","𝙐",-1)
	strO = strings.Replace(strO,"V","𝙑",-1)
	strO = strings.Replace(strO,"W","𝙒",-1)
	strO = strings.Replace(strO,"X","𝙓",-1)
	strO = strings.Replace(strO,"Y","𝙔",-1)
	strO = strings.Replace(strO,"Z","𝙕",-1)
	strO = strings.Replace(strO,"a","𝙖",-1)
	strO = strings.Replace(strO,"b","𝙗",-1)
	strO = strings.Replace(strO,"c","𝙘",-1)
	strO = strings.Replace(strO,"d","𝙙",-1)
	strO = strings.Replace(strO,"e","𝙚",-1)
	strO = strings.Replace(strO,"f","𝙛",-1)
	strO = strings.Replace(strO,"g","𝙜",-1)
	strO = strings.Replace(strO,"h","𝙝",-1)
	strO = strings.Replace(strO,"i","𝙞",-1)
	strO = strings.Replace(strO,"j","𝙟",-1)
	strO = strings.Replace(strO,"k","𝙠",-1)
	strO = strings.Replace(strO,"l","𝙡",-1)
	strO = strings.Replace(strO,"m","𝙢",-1)
	strO = strings.Replace(strO,"n","𝙣",-1)
	strO = strings.Replace(strO,"o","𝙤",-1)
	strO = strings.Replace(strO,"p","𝙥",-1)
	strO = strings.Replace(strO,"q","𝙦",-1)
	strO = strings.Replace(strO,"r","𝙧",-1)
	strO = strings.Replace(strO,"s","𝙨",-1)
	strO = strings.Replace(strO,"t","𝙩",-1)
	strO = strings.Replace(strO,"u","𝙪",-1)
	strO = strings.Replace(strO,"v","𝙫",-1)
	strO = strings.Replace(strO,"w","𝙬",-1)
	strO = strings.Replace(strO,"x","𝙭",-1)
	strO = strings.Replace(strO,"y","𝙮",-1)
	strO = strings.Replace(strO,"z","𝙯",-1)
	return strO
}