package c_CoolText__WiFi

import "strings"

const Name = "WiFi"
const NameSanitized = "WiFi"
const NameLoweredSanitized = "wifi"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","0",-1)
	strO = strings.Replace(strO,"1","1",-1)
	strO = strings.Replace(strO,"2","2",-1)
	strO = strings.Replace(strO,"3","3",-1)
	strO = strings.Replace(strO,"4","4",-1)
	strO = strings.Replace(strO,"5","5",-1)
	strO = strings.Replace(strO,"6","6",-1)
	strO = strings.Replace(strO,"7","7",-1)
	strO = strings.Replace(strO,"8","8",-1)
	strO = strings.Replace(strO,"9","9",-1)
	strO = strings.Replace(strO,"A","ᾋ",-1)
	strO = strings.Replace(strO,"B","ϐ",-1)
	strO = strings.Replace(strO,"C","Ƈ",-1)
	strO = strings.Replace(strO,"D","Ɖ",-1)
	strO = strings.Replace(strO,"E","Ἕ",-1)
	strO = strings.Replace(strO,"F","Ғ",-1)
	strO = strings.Replace(strO,"G","Ɠ",-1)
	strO = strings.Replace(strO,"H","Ἤ",-1)
	strO = strings.Replace(strO,"I","Ἷ",-1)
	strO = strings.Replace(strO,"J","Ј",-1)
	strO = strings.Replace(strO,"K","Ḱ",-1)
	strO = strings.Replace(strO,"L","Ŀ",-1)
	strO = strings.Replace(strO,"M","Ṃ",-1)
	strO = strings.Replace(strO,"N","Ɲ",-1)
	strO = strings.Replace(strO,"O","Ὃ",-1)
	strO = strings.Replace(strO,"P","Ƥ",-1)
	strO = strings.Replace(strO,"Q","Q",-1)
	strO = strings.Replace(strO,"R","Ȓ",-1)
	strO = strings.Replace(strO,"S","Ṩ",-1)
	strO = strings.Replace(strO,"T","Ҭ",-1)
	strO = strings.Replace(strO,"U","Ȗ",-1)
	strO = strings.Replace(strO,"V","V",-1)
	strO = strings.Replace(strO,"W","Ẃ",-1)
	strO = strings.Replace(strO,"X","Ẋ",-1)
	strO = strings.Replace(strO,"Y","Ὓ",-1)
	strO = strings.Replace(strO,"Z","Ẕ",-1)
	strO = strings.Replace(strO,"a","ᾄ",-1)
	strO = strings.Replace(strO,"b","в",-1)
	strO = strings.Replace(strO,"c","ƈ",-1)
	strO = strings.Replace(strO,"d","ḋ",-1)
	strO = strings.Replace(strO,"e","ἔ",-1)
	strO = strings.Replace(strO,"f","ғ",-1)
	strO = strings.Replace(strO,"g","ʛ",-1)
	strO = strings.Replace(strO,"h","ђ",-1)
	strO = strings.Replace(strO,"i","ἷ",-1)
	strO = strings.Replace(strO,"j","ʝ",-1)
	strO = strings.Replace(strO,"k","ќ",-1)
	strO = strings.Replace(strO,"l","ł",-1)
	strO = strings.Replace(strO,"m","м",-1)
	strO = strings.Replace(strO,"n","ᾗ",-1)
	strO = strings.Replace(strO,"o","ὄ",-1)
	strO = strings.Replace(strO,"p","ῥ",-1)
	strO = strings.Replace(strO,"q","q",-1)
	strO = strings.Replace(strO,"r","ʀ",-1)
	strO = strings.Replace(strO,"s","ṩ",-1)
	strO = strings.Replace(strO,"t","ҭ",-1)
	strO = strings.Replace(strO,"u","ὗ",-1)
	strO = strings.Replace(strO,"v","v",-1)
	strO = strings.Replace(strO,"w","ᾧ",-1)
	strO = strings.Replace(strO,"x","ẋ",-1)
	strO = strings.Replace(strO,"y","ẏ",-1)
	strO = strings.Replace(strO,"z","ẓ",-1)
	return strO
}