package c_CoolText__Upside_Down

import "strings"

const Name = "Upside Down"
const NameSanitized = "Upside_Down"
const NameLoweredSanitized = "upside_down"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","0",-1)
	strO = strings.Replace(strO,"1","⇂",-1)
	strO = strings.Replace(strO,"2","ᄅ",-1)
	strO = strings.Replace(strO,"3","Ɛ",-1)
	strO = strings.Replace(strO,"4","ㄣ",-1)
	strO = strings.Replace(strO,"5","ގ",-1)
	strO = strings.Replace(strO,"6","9",-1)
	strO = strings.Replace(strO,"7","ㄥ",-1)
	strO = strings.Replace(strO,"8","8",-1)
	strO = strings.Replace(strO,"9","6",-1)
	strO = strings.Replace(strO,"A","∀",-1)
	strO = strings.Replace(strO,"B","ᙠ",-1)
	strO = strings.Replace(strO,"C","Ɔ",-1)
	strO = strings.Replace(strO,"D","ᗡ",-1)
	strO = strings.Replace(strO,"E","Ǝ",-1)
	strO = strings.Replace(strO,"F","Ⅎ",-1)
	strO = strings.Replace(strO,"G","⅁",-1)
	strO = strings.Replace(strO,"H","H",-1)
	strO = strings.Replace(strO,"I","I",-1)
	strO = strings.Replace(strO,"J","ſ",-1)
	strO = strings.Replace(strO,"K","⋊",-1)
	strO = strings.Replace(strO,"L","˥",-1)
	strO = strings.Replace(strO,"M","W",-1)
	strO = strings.Replace(strO,"N","N",-1)
	strO = strings.Replace(strO,"O","O",-1)
	strO = strings.Replace(strO,"P","Ԁ",-1)
	strO = strings.Replace(strO,"Q","Ό",-1)
	strO = strings.Replace(strO,"R","ᴚ",-1)
	strO = strings.Replace(strO,"S","S",-1)
	strO = strings.Replace(strO,"T","⊥",-1)
	strO = strings.Replace(strO,"U","∩",-1)
	strO = strings.Replace(strO,"V","Λ",-1)
	strO = strings.Replace(strO,"W","M",-1)
	strO = strings.Replace(strO,"X","X",-1)
	strO = strings.Replace(strO,"Y","⅄",-1)
	strO = strings.Replace(strO,"Z","Z",-1)
	strO = strings.Replace(strO,"a","ɐ",-1)
	strO = strings.Replace(strO,"b","q",-1)
	strO = strings.Replace(strO,"c","ɔ",-1)
	strO = strings.Replace(strO,"d","p",-1)
	strO = strings.Replace(strO,"e","ǝ",-1)
	strO = strings.Replace(strO,"f","ɟ",-1)
	strO = strings.Replace(strO,"g","ɓ",-1)
	strO = strings.Replace(strO,"h","ɥ",-1)
	strO = strings.Replace(strO,"i","ı",-1)
	strO = strings.Replace(strO,"j","ɾ",-1)
	strO = strings.Replace(strO,"k","ʞ",-1)
	strO = strings.Replace(strO,"l","l",-1)
	strO = strings.Replace(strO,"m","ɯ",-1)
	strO = strings.Replace(strO,"n","u",-1)
	strO = strings.Replace(strO,"o","o",-1)
	strO = strings.Replace(strO,"p","d",-1)
	strO = strings.Replace(strO,"q","b",-1)
	strO = strings.Replace(strO,"r","ɹ",-1)
	strO = strings.Replace(strO,"s","s",-1)
	strO = strings.Replace(strO,"t","ʇ",-1)
	strO = strings.Replace(strO,"u","n",-1)
	strO = strings.Replace(strO,"v","ʌ",-1)
	strO = strings.Replace(strO,"w","ʍ",-1)
	strO = strings.Replace(strO,"x","x",-1)
	strO = strings.Replace(strO,"y","ʎ",-1)
	strO = strings.Replace(strO,"z","z",-1)
	return strO
}