package c_CoolText__Souvlaki

import "strings"

const Name = "Souvlaki"
const NameSanitized = "Souvlaki"
const NameLoweredSanitized = "souvlaki"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","0",-1)
	strO = strings.Replace(strO,"1","1",-1)
	strO = strings.Replace(strO,"2","2",-1)
	strO = strings.Replace(strO,"3","3",-1)
	strO = strings.Replace(strO,"4","4",-1)
	strO = strings.Replace(strO,"5","5",-1)
	strO = strings.Replace(strO,"6","6",-1)
	strO = strings.Replace(strO,"7","7",-1)
	strO = strings.Replace(strO,"8","8",-1)
	strO = strings.Replace(strO,"9","9",-1)
	strO = strings.Replace(strO,"A","α",-1)
	strO = strings.Replace(strO,"B","в",-1)
	strO = strings.Replace(strO,"C","¢",-1)
	strO = strings.Replace(strO,"D","∂",-1)
	strO = strings.Replace(strO,"E","є",-1)
	strO = strings.Replace(strO,"F","ƒ",-1)
	strO = strings.Replace(strO,"G","g",-1)
	strO = strings.Replace(strO,"H","н",-1)
	strO = strings.Replace(strO,"I","ι",-1)
	strO = strings.Replace(strO,"J","נ",-1)
	strO = strings.Replace(strO,"K","к",-1)
	strO = strings.Replace(strO,"L","ℓ",-1)
	strO = strings.Replace(strO,"M","м",-1)
	strO = strings.Replace(strO,"N","η",-1)
	strO = strings.Replace(strO,"O","σ",-1)
	strO = strings.Replace(strO,"P","ρ",-1)
	strO = strings.Replace(strO,"Q","q",-1)
	strO = strings.Replace(strO,"R","я",-1)
	strO = strings.Replace(strO,"S","ѕ",-1)
	strO = strings.Replace(strO,"T","т",-1)
	strO = strings.Replace(strO,"U","υ",-1)
	strO = strings.Replace(strO,"V","ν",-1)
	strO = strings.Replace(strO,"W","ω",-1)
	strO = strings.Replace(strO,"X","χ",-1)
	strO = strings.Replace(strO,"Y","у",-1)
	strO = strings.Replace(strO,"Z","z",-1)
	strO = strings.Replace(strO,"a","α",-1)
	strO = strings.Replace(strO,"b","в",-1)
	strO = strings.Replace(strO,"c","¢",-1)
	strO = strings.Replace(strO,"d","∂",-1)
	strO = strings.Replace(strO,"e","є",-1)
	strO = strings.Replace(strO,"f","ƒ",-1)
	strO = strings.Replace(strO,"g","g",-1)
	strO = strings.Replace(strO,"h","н",-1)
	strO = strings.Replace(strO,"i","ι",-1)
	strO = strings.Replace(strO,"j","נ",-1)
	strO = strings.Replace(strO,"k","к",-1)
	strO = strings.Replace(strO,"l","ℓ",-1)
	strO = strings.Replace(strO,"m","м",-1)
	strO = strings.Replace(strO,"n","η",-1)
	strO = strings.Replace(strO,"o","σ",-1)
	strO = strings.Replace(strO,"p","ρ",-1)
	strO = strings.Replace(strO,"q","q",-1)
	strO = strings.Replace(strO,"r","я",-1)
	strO = strings.Replace(strO,"s","ѕ",-1)
	strO = strings.Replace(strO,"t","т",-1)
	strO = strings.Replace(strO,"u","υ",-1)
	strO = strings.Replace(strO,"v","ν",-1)
	strO = strings.Replace(strO,"w","ω",-1)
	strO = strings.Replace(strO,"x","χ",-1)
	strO = strings.Replace(strO,"y","у",-1)
	strO = strings.Replace(strO,"z","z",-1)
	return strO
}