package c_CoolText__Ruski

import "strings"

const Name = "Ruski"
const NameSanitized = "Ruski"
const NameLoweredSanitized = "ruski"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","0",-1)
	strO = strings.Replace(strO,"1","1",-1)
	strO = strings.Replace(strO,"2","2",-1)
	strO = strings.Replace(strO,"3","3",-1)
	strO = strings.Replace(strO,"4","4",-1)
	strO = strings.Replace(strO,"5","5",-1)
	strO = strings.Replace(strO,"6","6",-1)
	strO = strings.Replace(strO,"7","7",-1)
	strO = strings.Replace(strO,"8","8",-1)
	strO = strings.Replace(strO,"9","9",-1)
	strO = strings.Replace(strO,"A","Д",-1)
	strO = strings.Replace(strO,"B","Б",-1)
	strO = strings.Replace(strO,"C","С",-1)
	strO = strings.Replace(strO,"D","Ď",-1)
	strO = strings.Replace(strO,"E","Е",-1)
	strO = strings.Replace(strO,"F","Ғ",-1)
	strO = strings.Replace(strO,"G","Ğ",-1)
	strO = strings.Replace(strO,"H","Н",-1)
	strO = strings.Replace(strO,"I","І",-1)
	strO = strings.Replace(strO,"J","Ј",-1)
	strO = strings.Replace(strO,"K","К",-1)
	strO = strings.Replace(strO,"L","L",-1)
	strO = strings.Replace(strO,"M","М",-1)
	strO = strings.Replace(strO,"N","П",-1)
	strO = strings.Replace(strO,"O","О",-1)
	strO = strings.Replace(strO,"P","Р",-1)
	strO = strings.Replace(strO,"Q","Ϙ",-1)
	strO = strings.Replace(strO,"R","Г",-1)
	strO = strings.Replace(strO,"S","Ѕ",-1)
	strO = strings.Replace(strO,"T","Т",-1)
	strO = strings.Replace(strO,"U","Ц",-1)
	strO = strings.Replace(strO,"V","Ѵ",-1)
	strO = strings.Replace(strO,"W","Ш",-1)
	strO = strings.Replace(strO,"X","Х",-1)
	strO = strings.Replace(strO,"Y","Ч",-1)
	strO = strings.Replace(strO,"Z","Z",-1)
	strO = strings.Replace(strO,"a","д",-1)
	strO = strings.Replace(strO,"b","б",-1)
	strO = strings.Replace(strO,"c","с",-1)
	strO = strings.Replace(strO,"d","ᴅ",-1)
	strO = strings.Replace(strO,"e","е",-1)
	strO = strings.Replace(strO,"f","ғ",-1)
	strO = strings.Replace(strO,"g","ɢ̆",-1)
	strO = strings.Replace(strO,"h","н",-1)
	strO = strings.Replace(strO,"i","і",-1)
	strO = strings.Replace(strO,"j","ᴊ",-1)
	strO = strings.Replace(strO,"k","к",-1)
	strO = strings.Replace(strO,"l","ʟ",-1)
	strO = strings.Replace(strO,"m","м",-1)
	strO = strings.Replace(strO,"n","п",-1)
	strO = strings.Replace(strO,"o","о",-1)
	strO = strings.Replace(strO,"p","р",-1)
	strO = strings.Replace(strO,"q","ϙ",-1)
	strO = strings.Replace(strO,"r","г",-1)
	strO = strings.Replace(strO,"s","ѕ",-1)
	strO = strings.Replace(strO,"t","т",-1)
	strO = strings.Replace(strO,"u","ц",-1)
	strO = strings.Replace(strO,"v","ѵ",-1)
	strO = strings.Replace(strO,"w","ш",-1)
	strO = strings.Replace(strO,"x","х",-1)
	strO = strings.Replace(strO,"y","ч",-1)
	strO = strings.Replace(strO,"z","ᴢ",-1)
	return strO
}