package c_CoolText__Funky_Bunch

import "strings"

const Name = "Funky Bunch"
const NameSanitized = "Funky_Bunch"
const NameLoweredSanitized = "funky_bunch"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","⊘",-1)
	strO = strings.Replace(strO,"1","𝟙",-1)
	strO = strings.Replace(strO,"2","ϩ",-1)
	strO = strings.Replace(strO,"3","Ӡ",-1)
	strO = strings.Replace(strO,"4","५",-1)
	strO = strings.Replace(strO,"5","Ƽ",-1)
	strO = strings.Replace(strO,"6","Ϭ",-1)
	strO = strings.Replace(strO,"7","7",-1)
	strO = strings.Replace(strO,"8","𝟠",-1)
	strO = strings.Replace(strO,"9","९",-1)
	strO = strings.Replace(strO,"A","Ⱥ",-1)
	strO = strings.Replace(strO,"B","β",-1)
	strO = strings.Replace(strO,"C","↻",-1)
	strO = strings.Replace(strO,"D","Ꭰ",-1)
	strO = strings.Replace(strO,"E","Ɛ",-1)
	strO = strings.Replace(strO,"F","Ƒ",-1)
	strO = strings.Replace(strO,"G","Ɠ",-1)
	strO = strings.Replace(strO,"H","Ƕ",-1)
	strO = strings.Replace(strO,"I","į",-1)
	strO = strings.Replace(strO,"J","ل",-1)
	strO = strings.Replace(strO,"K","Ҡ",-1)
	strO = strings.Replace(strO,"L","Ꝉ",-1)
	strO = strings.Replace(strO,"M","Ɱ",-1)
	strO = strings.Replace(strO,"N","ហ",-1)
	strO = strings.Replace(strO,"O","ට",-1)
	strO = strings.Replace(strO,"P","φ",-1)
	strO = strings.Replace(strO,"Q","Ҩ",-1)
	strO = strings.Replace(strO,"R","འ",-1)
	strO = strings.Replace(strO,"S","Ϛ",-1)
	strO = strings.Replace(strO,"T","Ͳ",-1)
	strO = strings.Replace(strO,"U","Ա",-1)
	strO = strings.Replace(strO,"V","Ỽ",-1)
	strO = strings.Replace(strO,"W","చ",-1)
	strO = strings.Replace(strO,"X","ჯ",-1)
	strO = strings.Replace(strO,"Y","Ӌ",-1)
	strO = strings.Replace(strO,"Z","ɀ",-1)
	strO = strings.Replace(strO,"a","ą",-1)
	strO = strings.Replace(strO,"b","ҍ",-1)
	strO = strings.Replace(strO,"c","ç",-1)
	strO = strings.Replace(strO,"d","ժ",-1)
	strO = strings.Replace(strO,"e","ҽ",-1)
	strO = strings.Replace(strO,"f","ƒ",-1)
	strO = strings.Replace(strO,"g","ց",-1)
	strO = strings.Replace(strO,"h","հ",-1)
	strO = strings.Replace(strO,"i","ì",-1)
	strO = strings.Replace(strO,"j","ʝ",-1)
	strO = strings.Replace(strO,"k","ҟ",-1)
	strO = strings.Replace(strO,"l","Ӏ",-1)
	strO = strings.Replace(strO,"m","ʍ",-1)
	strO = strings.Replace(strO,"n","ղ",-1)
	strO = strings.Replace(strO,"o","օ",-1)
	strO = strings.Replace(strO,"p","ք",-1)
	strO = strings.Replace(strO,"q","զ",-1)
	strO = strings.Replace(strO,"r","ɾ",-1)
	strO = strings.Replace(strO,"s","ʂ",-1)
	strO = strings.Replace(strO,"t","է",-1)
	strO = strings.Replace(strO,"u","մ",-1)
	strO = strings.Replace(strO,"v","ѵ",-1)
	strO = strings.Replace(strO,"w","ա",-1)
	strO = strings.Replace(strO,"x","×",-1)
	strO = strings.Replace(strO,"y","վ",-1)
	strO = strings.Replace(strO,"z","Հ",-1)
	return strO
}