package c_CoolText__Quebec

import "strings"

const Name = "Quebec"
const NameSanitized = "Quebec"
const NameLoweredSanitized = "quebec"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","0",-1)
	strO = strings.Replace(strO,"1","1",-1)
	strO = strings.Replace(strO,"2","2",-1)
	strO = strings.Replace(strO,"3","3",-1)
	strO = strings.Replace(strO,"4","4",-1)
	strO = strings.Replace(strO,"5","5",-1)
	strO = strings.Replace(strO,"6","6",-1)
	strO = strings.Replace(strO,"7","7",-1)
	strO = strings.Replace(strO,"8","8",-1)
	strO = strings.Replace(strO,"9","9",-1)
	strO = strings.Replace(strO,"A","Ɑ",-1)
	strO = strings.Replace(strO,"B","Ɓ",-1)
	strO = strings.Replace(strO,"C","Ƈ",-1)
	strO = strings.Replace(strO,"D","Ɗ",-1)
	strO = strings.Replace(strO,"E","Ҽ",-1)
	strO = strings.Replace(strO,"F","Ƒ",-1)
	strO = strings.Replace(strO,"G","Ɠ",-1)
	strO = strings.Replace(strO,"H","Ӈ",-1)
	strO = strings.Replace(strO,"I","Ӏ",-1)
	strO = strings.Replace(strO,"J","J",-1)
	strO = strings.Replace(strO,"K","Ƙ",-1)
	strO = strings.Replace(strO,"L","l",-1)
	strO = strings.Replace(strO,"M","Ɱ",-1)
	strO = strings.Replace(strO,"N","Ɲ",-1)
	strO = strings.Replace(strO,"O","Ơ",-1)
	strO = strings.Replace(strO,"P","Ƥ",-1)
	strO = strings.Replace(strO,"Q","Q",-1)
	strO = strings.Replace(strO,"R","R",-1)
	strO = strings.Replace(strO,"S","Տ",-1)
	strO = strings.Replace(strO,"T","Ƭ",-1)
	strO = strings.Replace(strO,"U","Ʋ",-1)
	strO = strings.Replace(strO,"V","V",-1)
	strO = strings.Replace(strO,"W","Ⱳ",-1)
	strO = strings.Replace(strO,"X","X",-1)
	strO = strings.Replace(strO,"Y","Ƴ",-1)
	strO = strings.Replace(strO,"Z","Ȥ",-1)
	strO = strings.Replace(strO,"a","ɑ",-1)
	strO = strings.Replace(strO,"b","ҍ",-1)
	strO = strings.Replace(strO,"c","ϲ",-1)
	strO = strings.Replace(strO,"d","ժ",-1)
	strO = strings.Replace(strO,"e","ҽ",-1)
	strO = strings.Replace(strO,"f","ƒ",-1)
	strO = strings.Replace(strO,"g","ց",-1)
	strO = strings.Replace(strO,"h","հ",-1)
	strO = strings.Replace(strO,"i","í",-1)
	strO = strings.Replace(strO,"j","ᴊ",-1)
	strO = strings.Replace(strO,"k","ƙ",-1)
	strO = strings.Replace(strO,"l","Ɩ",-1)
	strO = strings.Replace(strO,"m","ʍ",-1)
	strO = strings.Replace(strO,"n","ղ",-1)
	strO = strings.Replace(strO,"o","օ",-1)
	strO = strings.Replace(strO,"p","թ",-1)
	strO = strings.Replace(strO,"q","q",-1)
	strO = strings.Replace(strO,"r","ɾ",-1)
	strO = strings.Replace(strO,"s","s",-1)
	strO = strings.Replace(strO,"t","ե",-1)
	strO = strings.Replace(strO,"u","մ",-1)
	strO = strings.Replace(strO,"v","ѵ",-1)
	strO = strings.Replace(strO,"w","ա",-1)
	strO = strings.Replace(strO,"x","x",-1)
	strO = strings.Replace(strO,"y","ყ",-1)
	strO = strings.Replace(strO,"z","z",-1)
	return strO
}