package c_CoolText__Rando

import "strings"

const Name = "Rando"
const NameSanitized = "Rando"
const NameLoweredSanitized = "rando"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","ʘ",-1)
	strO = strings.Replace(strO,"1","➀",-1)
	strO = strings.Replace(strO,"2","❷",-1)
	strO = strings.Replace(strO,"3","➂",-1)
	strO = strings.Replace(strO,"4","➃",-1)
	strO = strings.Replace(strO,"5","❺",-1)
	strO = strings.Replace(strO,"6","➅",-1)
	strO = strings.Replace(strO,"7","➆",-1)
	strO = strings.Replace(strO,"8","❽",-1)
	strO = strings.Replace(strO,"9","❾",-1)
	strO = strings.Replace(strO,"A","𝕒",-1)
	strO = strings.Replace(strO,"B","Ⓑ",-1)
	strO = strings.Replace(strO,"C","ｃ",-1)
	strO = strings.Replace(strO,"D","𝓭",-1)
	strO = strings.Replace(strO,"E","𝒆",-1)
	strO = strings.Replace(strO,"F","ғ",-1)
	strO = strings.Replace(strO,"G","ﻮ",-1)
	strO = strings.Replace(strO,"H","Ĥ",-1)
	strO = strings.Replace(strO,"I","ί",-1)
	strO = strings.Replace(strO,"J","Ĵ",-1)
	strO = strings.Replace(strO,"K","𝓚",-1)
	strO = strings.Replace(strO,"L","ˡ",-1)
	strO = strings.Replace(strO,"M","𝓂",-1)
	strO = strings.Replace(strO,"N","几",-1)
	strO = strings.Replace(strO,"O","σ",-1)
	strO = strings.Replace(strO,"P","ק",-1)
	strO = strings.Replace(strO,"Q","𝐐",-1)
	strO = strings.Replace(strO,"R","ᖇ",-1)
	strO = strings.Replace(strO,"S","ⓢ",-1)
	strO = strings.Replace(strO,"T","ｔ",-1)
	strO = strings.Replace(strO,"U","ย",-1)
	strO = strings.Replace(strO,"V","ᐯ",-1)
	strO = strings.Replace(strO,"W","ⓦ",-1)
	strO = strings.Replace(strO,"X","χ",-1)
	strO = strings.Replace(strO,"Y","𝔂",-1)
	strO = strings.Replace(strO,"Z","z",-1)
	strO = strings.Replace(strO,"a","ⓐ",-1)
	strO = strings.Replace(strO,"b","ｂ",-1)
	strO = strings.Replace(strO,"c","ｃ",-1)
	strO = strings.Replace(strO,"d","∂",-1)
	strO = strings.Replace(strO,"e","𝐄",-1)
	strO = strings.Replace(strO,"f","𝕗",-1)
	strO = strings.Replace(strO,"g","𝓖",-1)
	strO = strings.Replace(strO,"h","Ｈ",-1)
	strO = strings.Replace(strO,"i","เ",-1)
	strO = strings.Replace(strO,"j","נ",-1)
	strO = strings.Replace(strO,"k","𝓀",-1)
	strO = strings.Replace(strO,"l","𝓛",-1)
	strO = strings.Replace(strO,"m","𝐌",-1)
	strO = strings.Replace(strO,"n","几",-1)
	strO = strings.Replace(strO,"o","𝕆",-1)
	strO = strings.Replace(strO,"p","𝕡",-1)
	strO = strings.Replace(strO,"q","𝐐",-1)
	strO = strings.Replace(strO,"r","ⓡ",-1)
	strO = strings.Replace(strO,"s","ѕ",-1)
	strO = strings.Replace(strO,"t","т",-1)
	strO = strings.Replace(strO,"u","𝐮",-1)
	strO = strings.Replace(strO,"v","𝓋",-1)
	strO = strings.Replace(strO,"w","ｗ",-1)
	strO = strings.Replace(strO,"x","χ",-1)
	strO = strings.Replace(strO,"y","Ｙ",-1)
	strO = strings.Replace(strO,"z","ℤ",-1)
	return strO
}