package c_CoolText__Franktur_Bold

import "strings"

const Name = "Franktur Bold"
const NameSanitized = "Franktur_Bold"
const NameLoweredSanitized = "franktur_bold"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","օ",-1)
	strO = strings.Replace(strO,"1","յ",-1)
	strO = strings.Replace(strO,"2","շ",-1)
	strO = strings.Replace(strO,"3","Յ",-1)
	strO = strings.Replace(strO,"4","կ",-1)
	strO = strings.Replace(strO,"5","Տ",-1)
	strO = strings.Replace(strO,"6","ճ",-1)
	strO = strings.Replace(strO,"7","Դ",-1)
	strO = strings.Replace(strO,"8","Ց",-1)
	strO = strings.Replace(strO,"9","գ",-1)
	strO = strings.Replace(strO,"A","𝕬",-1)
	strO = strings.Replace(strO,"B","𝕭",-1)
	strO = strings.Replace(strO,"C","𝕮",-1)
	strO = strings.Replace(strO,"D","𝕯",-1)
	strO = strings.Replace(strO,"E","𝕰",-1)
	strO = strings.Replace(strO,"F","𝕱",-1)
	strO = strings.Replace(strO,"G","𝕲",-1)
	strO = strings.Replace(strO,"H","𝕳",-1)
	strO = strings.Replace(strO,"I","𝕴",-1)
	strO = strings.Replace(strO,"J","𝕵",-1)
	strO = strings.Replace(strO,"K","𝕶",-1)
	strO = strings.Replace(strO,"L","𝕷",-1)
	strO = strings.Replace(strO,"M","𝕸",-1)
	strO = strings.Replace(strO,"N","𝕹",-1)
	strO = strings.Replace(strO,"O","𝕺",-1)
	strO = strings.Replace(strO,"P","𝕻",-1)
	strO = strings.Replace(strO,"Q","𝕼",-1)
	strO = strings.Replace(strO,"R","𝕽",-1)
	strO = strings.Replace(strO,"S","𝕾",-1)
	strO = strings.Replace(strO,"T","𝕿",-1)
	strO = strings.Replace(strO,"U","𝖀",-1)
	strO = strings.Replace(strO,"V","𝖁",-1)
	strO = strings.Replace(strO,"W","𝖂",-1)
	strO = strings.Replace(strO,"X","𝖃",-1)
	strO = strings.Replace(strO,"Y","𝖄",-1)
	strO = strings.Replace(strO,"Z","𝖅",-1)
	strO = strings.Replace(strO,"a","𝖆",-1)
	strO = strings.Replace(strO,"b","𝖇",-1)
	strO = strings.Replace(strO,"c","𝖈",-1)
	strO = strings.Replace(strO,"d","𝖉",-1)
	strO = strings.Replace(strO,"e","𝖊",-1)
	strO = strings.Replace(strO,"f","𝖋",-1)
	strO = strings.Replace(strO,"g","𝖌",-1)
	strO = strings.Replace(strO,"h","𝖍",-1)
	strO = strings.Replace(strO,"i","𝖎",-1)
	strO = strings.Replace(strO,"j","𝖏",-1)
	strO = strings.Replace(strO,"k","𝖐",-1)
	strO = strings.Replace(strO,"l","𝖑",-1)
	strO = strings.Replace(strO,"m","𝖒",-1)
	strO = strings.Replace(strO,"n","𝖓",-1)
	strO = strings.Replace(strO,"o","𝖔",-1)
	strO = strings.Replace(strO,"p","𝖕",-1)
	strO = strings.Replace(strO,"q","𝖖",-1)
	strO = strings.Replace(strO,"r","𝖗",-1)
	strO = strings.Replace(strO,"s","𝖘",-1)
	strO = strings.Replace(strO,"t","𝖙",-1)
	strO = strings.Replace(strO,"u","𝖚",-1)
	strO = strings.Replace(strO,"v","𝖛",-1)
	strO = strings.Replace(strO,"w","𝖜",-1)
	strO = strings.Replace(strO,"x","𝖝",-1)
	strO = strings.Replace(strO,"y","𝖞",-1)
	strO = strings.Replace(strO,"z","𝖟",-1)
	return strO
}