package c_CoolText__Slipknot

import "strings"

const Name = "Slipknot"
const NameSanitized = "Slipknot"
const NameLoweredSanitized = "slipknot"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","0",-1)
	strO = strings.Replace(strO,"1","1",-1)
	strO = strings.Replace(strO,"2","2",-1)
	strO = strings.Replace(strO,"3","3",-1)
	strO = strings.Replace(strO,"4","4",-1)
	strO = strings.Replace(strO,"5","5",-1)
	strO = strings.Replace(strO,"6","6",-1)
	strO = strings.Replace(strO,"7","7",-1)
	strO = strings.Replace(strO,"8","8",-1)
	strO = strings.Replace(strO,"9","9",-1)
	strO = strings.Replace(strO,"A","₳",-1)
	strO = strings.Replace(strO,"B","฿",-1)
	strO = strings.Replace(strO,"C","₵",-1)
	strO = strings.Replace(strO,"D","Đ",-1)
	strO = strings.Replace(strO,"E","Ɇ",-1)
	strO = strings.Replace(strO,"F","₣",-1)
	strO = strings.Replace(strO,"G","₲",-1)
	strO = strings.Replace(strO,"H","Ⱨ",-1)
	strO = strings.Replace(strO,"I","ł",-1)
	strO = strings.Replace(strO,"J","J",-1)
	strO = strings.Replace(strO,"K","₭",-1)
	strO = strings.Replace(strO,"L","Ⱡ",-1)
	strO = strings.Replace(strO,"M","₥",-1)
	strO = strings.Replace(strO,"N","₦",-1)
	strO = strings.Replace(strO,"O","Ø",-1)
	strO = strings.Replace(strO,"P","₱",-1)
	strO = strings.Replace(strO,"Q","Q",-1)
	strO = strings.Replace(strO,"R","Ɽ",-1)
	strO = strings.Replace(strO,"S","₴",-1)
	strO = strings.Replace(strO,"T","₮",-1)
	strO = strings.Replace(strO,"U","Ʉ",-1)
	strO = strings.Replace(strO,"V","V",-1)
	strO = strings.Replace(strO,"W","₩",-1)
	strO = strings.Replace(strO,"X","Ӿ",-1)
	strO = strings.Replace(strO,"Y","Ɏ",-1)
	strO = strings.Replace(strO,"Z","Ⱬ",-1)
	strO = strings.Replace(strO,"a","₳",-1)
	strO = strings.Replace(strO,"b","฿",-1)
	strO = strings.Replace(strO,"c","₵",-1)
	strO = strings.Replace(strO,"d","Đ",-1)
	strO = strings.Replace(strO,"e","Ɇ",-1)
	strO = strings.Replace(strO,"f","₣",-1)
	strO = strings.Replace(strO,"g","₲",-1)
	strO = strings.Replace(strO,"h","Ⱨ",-1)
	strO = strings.Replace(strO,"i","ł",-1)
	strO = strings.Replace(strO,"j","J",-1)
	strO = strings.Replace(strO,"k","₭",-1)
	strO = strings.Replace(strO,"l","Ⱡ",-1)
	strO = strings.Replace(strO,"m","₥",-1)
	strO = strings.Replace(strO,"n","₦",-1)
	strO = strings.Replace(strO,"o","Ø",-1)
	strO = strings.Replace(strO,"p","₱",-1)
	strO = strings.Replace(strO,"q","Q",-1)
	strO = strings.Replace(strO,"r","Ɽ",-1)
	strO = strings.Replace(strO,"s","₴",-1)
	strO = strings.Replace(strO,"t","₮",-1)
	strO = strings.Replace(strO,"u","Ʉ",-1)
	strO = strings.Replace(strO,"v","V",-1)
	strO = strings.Replace(strO,"w","₩",-1)
	strO = strings.Replace(strO,"x","Ӿ",-1)
	strO = strings.Replace(strO,"y","Ɏ",-1)
	strO = strings.Replace(strO,"z","Ⱬ",-1)
	return strO
}