package c_CoolText__Wonky_Doodle

import "strings"

const Name = "Wonky Doodle"
const NameSanitized = "Wonky_Doodle"
const NameLoweredSanitized = "wonky_doodle"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","0",-1)
	strO = strings.Replace(strO,"1","1",-1)
	strO = strings.Replace(strO,"2","2",-1)
	strO = strings.Replace(strO,"3","3",-1)
	strO = strings.Replace(strO,"4","4",-1)
	strO = strings.Replace(strO,"5","5",-1)
	strO = strings.Replace(strO,"6","6",-1)
	strO = strings.Replace(strO,"7","7",-1)
	strO = strings.Replace(strO,"8","8",-1)
	strO = strings.Replace(strO,"9","9",-1)
	strO = strings.Replace(strO,"A","ค",-1)
	strO = strings.Replace(strO,"B","๒",-1)
	strO = strings.Replace(strO,"C","ς",-1)
	strO = strings.Replace(strO,"D","๔",-1)
	strO = strings.Replace(strO,"E","є",-1)
	strO = strings.Replace(strO,"F","Ŧ",-1)
	strO = strings.Replace(strO,"G","ɠ",-1)
	strO = strings.Replace(strO,"H","ђ",-1)
	strO = strings.Replace(strO,"I","เ",-1)
	strO = strings.Replace(strO,"J","ן",-1)
	strO = strings.Replace(strO,"K","к",-1)
	strO = strings.Replace(strO,"L","l",-1)
	strO = strings.Replace(strO,"M","๓",-1)
	strO = strings.Replace(strO,"N","ภ",-1)
	strO = strings.Replace(strO,"O","๏",-1)
	strO = strings.Replace(strO,"P","թ",-1)
	strO = strings.Replace(strO,"Q","ợ",-1)
	strO = strings.Replace(strO,"R","г",-1)
	strO = strings.Replace(strO,"S","ร",-1)
	strO = strings.Replace(strO,"T","t",-1)
	strO = strings.Replace(strO,"U","ย",-1)
	strO = strings.Replace(strO,"V","v",-1)
	strO = strings.Replace(strO,"W","ฬ",-1)
	strO = strings.Replace(strO,"X","x",-1)
	strO = strings.Replace(strO,"Y","ץ",-1)
	strO = strings.Replace(strO,"Z","z",-1)
	strO = strings.Replace(strO,"a","ค",-1)
	strO = strings.Replace(strO,"b","๒",-1)
	strO = strings.Replace(strO,"c","ς",-1)
	strO = strings.Replace(strO,"d","๔",-1)
	strO = strings.Replace(strO,"e","є",-1)
	strO = strings.Replace(strO,"f","Ŧ",-1)
	strO = strings.Replace(strO,"g","ɠ",-1)
	strO = strings.Replace(strO,"h","ђ",-1)
	strO = strings.Replace(strO,"i","เ",-1)
	strO = strings.Replace(strO,"j","ן",-1)
	strO = strings.Replace(strO,"k","к",-1)
	strO = strings.Replace(strO,"l","l",-1)
	strO = strings.Replace(strO,"m","๓",-1)
	strO = strings.Replace(strO,"n","ภ",-1)
	strO = strings.Replace(strO,"o","๏",-1)
	strO = strings.Replace(strO,"p","թ",-1)
	strO = strings.Replace(strO,"q","ợ",-1)
	strO = strings.Replace(strO,"r","г",-1)
	strO = strings.Replace(strO,"s","ร",-1)
	strO = strings.Replace(strO,"t","t",-1)
	strO = strings.Replace(strO,"u","ย",-1)
	strO = strings.Replace(strO,"v","v",-1)
	strO = strings.Replace(strO,"w","ฬ",-1)
	strO = strings.Replace(strO,"x","x",-1)
	strO = strings.Replace(strO,"y","ץ",-1)
	strO = strings.Replace(strO,"z","z",-1)
	return strO
}