package c_CoolText__Price_is_Wrong

import "strings"

const Name = "Price is Wrong"
const NameSanitized = "Price_is_Wrong"
const NameLoweredSanitized = "price_is_wrong"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","0",-1)
	strO = strings.Replace(strO,"1","1",-1)
	strO = strings.Replace(strO,"2","2",-1)
	strO = strings.Replace(strO,"3","3",-1)
	strO = strings.Replace(strO,"4","4",-1)
	strO = strings.Replace(strO,"5","5",-1)
	strO = strings.Replace(strO,"6","6",-1)
	strO = strings.Replace(strO,"7","7",-1)
	strO = strings.Replace(strO,"8","8",-1)
	strO = strings.Replace(strO,"9","9",-1)
	strO = strings.Replace(strO,"A","🄰",-1)
	strO = strings.Replace(strO,"B","🄱",-1)
	strO = strings.Replace(strO,"C","🄲",-1)
	strO = strings.Replace(strO,"D","🄳",-1)
	strO = strings.Replace(strO,"E","🄴",-1)
	strO = strings.Replace(strO,"F","🄵",-1)
	strO = strings.Replace(strO,"G","🄶",-1)
	strO = strings.Replace(strO,"H","🄷",-1)
	strO = strings.Replace(strO,"I","🄸",-1)
	strO = strings.Replace(strO,"J","🄹",-1)
	strO = strings.Replace(strO,"K","🄺",-1)
	strO = strings.Replace(strO,"L","🄻",-1)
	strO = strings.Replace(strO,"M","🄼",-1)
	strO = strings.Replace(strO,"N","🄽",-1)
	strO = strings.Replace(strO,"O","🄾",-1)
	strO = strings.Replace(strO,"P","🄿",-1)
	strO = strings.Replace(strO,"Q","🅀",-1)
	strO = strings.Replace(strO,"R","🅁",-1)
	strO = strings.Replace(strO,"S","🅂",-1)
	strO = strings.Replace(strO,"T","🅃",-1)
	strO = strings.Replace(strO,"U","🅄",-1)
	strO = strings.Replace(strO,"V","🅅",-1)
	strO = strings.Replace(strO,"W","🅆",-1)
	strO = strings.Replace(strO,"X","🅇",-1)
	strO = strings.Replace(strO,"Y","🅈",-1)
	strO = strings.Replace(strO,"Z","🅉",-1)
	strO = strings.Replace(strO,"a","🄰",-1)
	strO = strings.Replace(strO,"b","🄱",-1)
	strO = strings.Replace(strO,"c","🄲",-1)
	strO = strings.Replace(strO,"d","🄳",-1)
	strO = strings.Replace(strO,"e","🄴",-1)
	strO = strings.Replace(strO,"f","🄵",-1)
	strO = strings.Replace(strO,"g","🄶",-1)
	strO = strings.Replace(strO,"h","🄷",-1)
	strO = strings.Replace(strO,"i","🄸",-1)
	strO = strings.Replace(strO,"j","🄹",-1)
	strO = strings.Replace(strO,"k","🄺",-1)
	strO = strings.Replace(strO,"l","🄻",-1)
	strO = strings.Replace(strO,"m","🄼",-1)
	strO = strings.Replace(strO,"n","🄽",-1)
	strO = strings.Replace(strO,"o","🄾",-1)
	strO = strings.Replace(strO,"p","🄿",-1)
	strO = strings.Replace(strO,"q","🅀",-1)
	strO = strings.Replace(strO,"r","🅁",-1)
	strO = strings.Replace(strO,"s","🅂",-1)
	strO = strings.Replace(strO,"t","🅃",-1)
	strO = strings.Replace(strO,"u","🅄",-1)
	strO = strings.Replace(strO,"v","🅅",-1)
	strO = strings.Replace(strO,"w","🅆",-1)
	strO = strings.Replace(strO,"x","🅇",-1)
	strO = strings.Replace(strO,"y","🅈",-1)
	strO = strings.Replace(strO,"z","🅉",-1)
	return strO
}