package c_CoolText__Lite

import "strings"

const Name = "Lite"
const NameSanitized = "Lite"
const NameLoweredSanitized = "lite"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","０",-1)
	strO = strings.Replace(strO,"1","１",-1)
	strO = strings.Replace(strO,"2","２",-1)
	strO = strings.Replace(strO,"3","３",-1)
	strO = strings.Replace(strO,"4","４",-1)
	strO = strings.Replace(strO,"5","５",-1)
	strO = strings.Replace(strO,"6","６",-1)
	strO = strings.Replace(strO,"7","７",-1)
	strO = strings.Replace(strO,"8","８",-1)
	strO = strings.Replace(strO,"9","９",-1)
	strO = strings.Replace(strO,"A","Ａ",-1)
	strO = strings.Replace(strO,"B","Ｂ",-1)
	strO = strings.Replace(strO,"C","Ｃ",-1)
	strO = strings.Replace(strO,"D","Ｄ",-1)
	strO = strings.Replace(strO,"E","Ｅ",-1)
	strO = strings.Replace(strO,"F","Ｆ",-1)
	strO = strings.Replace(strO,"G","Ｇ",-1)
	strO = strings.Replace(strO,"H","Ｈ",-1)
	strO = strings.Replace(strO,"I","Ｉ",-1)
	strO = strings.Replace(strO,"J","Ｊ",-1)
	strO = strings.Replace(strO,"K","Ｋ",-1)
	strO = strings.Replace(strO,"L","Ｌ",-1)
	strO = strings.Replace(strO,"M","Ｍ",-1)
	strO = strings.Replace(strO,"N","Ｎ",-1)
	strO = strings.Replace(strO,"O","Ｏ",-1)
	strO = strings.Replace(strO,"P","Ｐ",-1)
	strO = strings.Replace(strO,"Q","Ｑ",-1)
	strO = strings.Replace(strO,"R","Ｒ",-1)
	strO = strings.Replace(strO,"S","Ｓ",-1)
	strO = strings.Replace(strO,"T","Ｔ",-1)
	strO = strings.Replace(strO,"U","Ｕ",-1)
	strO = strings.Replace(strO,"V","Ｖ",-1)
	strO = strings.Replace(strO,"W","Ｗ",-1)
	strO = strings.Replace(strO,"X","Ｘ",-1)
	strO = strings.Replace(strO,"Y","Ｙ",-1)
	strO = strings.Replace(strO,"Z","Ｚ",-1)
	strO = strings.Replace(strO,"a","ａ",-1)
	strO = strings.Replace(strO,"b","ｂ",-1)
	strO = strings.Replace(strO,"c","ｃ",-1)
	strO = strings.Replace(strO,"d","ｄ",-1)
	strO = strings.Replace(strO,"e","ｅ",-1)
	strO = strings.Replace(strO,"f","ｆ",-1)
	strO = strings.Replace(strO,"g","ｇ",-1)
	strO = strings.Replace(strO,"h","ｈ",-1)
	strO = strings.Replace(strO,"i","ｉ",-1)
	strO = strings.Replace(strO,"j","ｊ",-1)
	strO = strings.Replace(strO,"k","ｋ",-1)
	strO = strings.Replace(strO,"l","ｌ",-1)
	strO = strings.Replace(strO,"m","ｍ",-1)
	strO = strings.Replace(strO,"n","ｎ",-1)
	strO = strings.Replace(strO,"o","ｏ",-1)
	strO = strings.Replace(strO,"p","ｐ",-1)
	strO = strings.Replace(strO,"q","ｑ",-1)
	strO = strings.Replace(strO,"r","ｒ",-1)
	strO = strings.Replace(strO,"s","ｓ",-1)
	strO = strings.Replace(strO,"t","ｔ",-1)
	strO = strings.Replace(strO,"u","ｕ",-1)
	strO = strings.Replace(strO,"v","ｖ",-1)
	strO = strings.Replace(strO,"w","ｗ",-1)
	strO = strings.Replace(strO,"x","ｘ",-1)
	strO = strings.Replace(strO,"y","ｙ",-1)
	strO = strings.Replace(strO,"z","ｚ",-1)
	return strO
}