package c_CoolText__Script

import "strings"

const Name = "Script"
const NameSanitized = "Script"
const NameLoweredSanitized = "script"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","0",-1)
	strO = strings.Replace(strO,"1","1",-1)
	strO = strings.Replace(strO,"2","2",-1)
	strO = strings.Replace(strO,"3","3",-1)
	strO = strings.Replace(strO,"4","4",-1)
	strO = strings.Replace(strO,"5","5",-1)
	strO = strings.Replace(strO,"6","6",-1)
	strO = strings.Replace(strO,"7","7",-1)
	strO = strings.Replace(strO,"8","8",-1)
	strO = strings.Replace(strO,"9","9",-1)
	strO = strings.Replace(strO,"A","𝒜",-1)
	strO = strings.Replace(strO,"B","𝐵",-1)
	strO = strings.Replace(strO,"C","𝒞",-1)
	strO = strings.Replace(strO,"D","𝒟",-1)
	strO = strings.Replace(strO,"E","𝐸",-1)
	strO = strings.Replace(strO,"F","𝐹",-1)
	strO = strings.Replace(strO,"G","𝒢",-1)
	strO = strings.Replace(strO,"H","𝐻",-1)
	strO = strings.Replace(strO,"I","𝐼",-1)
	strO = strings.Replace(strO,"J","𝒥",-1)
	strO = strings.Replace(strO,"K","𝒦",-1)
	strO = strings.Replace(strO,"L","𝐿",-1)
	strO = strings.Replace(strO,"M","𝑀",-1)
	strO = strings.Replace(strO,"N","𝒩",-1)
	strO = strings.Replace(strO,"O","𝒪",-1)
	strO = strings.Replace(strO,"P","𝒫",-1)
	strO = strings.Replace(strO,"Q","𝒬",-1)
	strO = strings.Replace(strO,"R","𝑅",-1)
	strO = strings.Replace(strO,"S","𝒮",-1)
	strO = strings.Replace(strO,"T","𝒯",-1)
	strO = strings.Replace(strO,"U","𝒰",-1)
	strO = strings.Replace(strO,"V","𝒱",-1)
	strO = strings.Replace(strO,"W","𝒲",-1)
	strO = strings.Replace(strO,"X","𝒳",-1)
	strO = strings.Replace(strO,"Y","𝒴",-1)
	strO = strings.Replace(strO,"Z","𝒵",-1)
	strO = strings.Replace(strO,"a","𝒶",-1)
	strO = strings.Replace(strO,"b","𝒷",-1)
	strO = strings.Replace(strO,"c","𝒸",-1)
	strO = strings.Replace(strO,"d","𝒹",-1)
	strO = strings.Replace(strO,"e","𝑒",-1)
	strO = strings.Replace(strO,"f","𝒻",-1)
	strO = strings.Replace(strO,"g","𝑔",-1)
	strO = strings.Replace(strO,"h","𝒽",-1)
	strO = strings.Replace(strO,"i","𝒾",-1)
	strO = strings.Replace(strO,"j","𝒿",-1)
	strO = strings.Replace(strO,"k","𝓀",-1)
	strO = strings.Replace(strO,"l","𝓁",-1)
	strO = strings.Replace(strO,"m","𝓂",-1)
	strO = strings.Replace(strO,"n","𝓃",-1)
	strO = strings.Replace(strO,"o","𝑜",-1)
	strO = strings.Replace(strO,"p","𝓅",-1)
	strO = strings.Replace(strO,"q","𝓆",-1)
	strO = strings.Replace(strO,"r","𝓇",-1)
	strO = strings.Replace(strO,"s","𝓈",-1)
	strO = strings.Replace(strO,"t","𝓉",-1)
	strO = strings.Replace(strO,"u","𝓊",-1)
	strO = strings.Replace(strO,"v","𝓋",-1)
	strO = strings.Replace(strO,"w","𝓌",-1)
	strO = strings.Replace(strO,"x","𝓍",-1)
	strO = strings.Replace(strO,"y","𝓎",-1)
	strO = strings.Replace(strO,"z","𝓏",-1)
	return strO
}