package c_CoolText__Franktur

import "strings"

const Name = "Franktur"
const NameSanitized = "Franktur"
const NameLoweredSanitized = "franktur"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","օ",-1)
	strO = strings.Replace(strO,"1","յ",-1)
	strO = strings.Replace(strO,"2","շ",-1)
	strO = strings.Replace(strO,"3","Յ",-1)
	strO = strings.Replace(strO,"4","կ",-1)
	strO = strings.Replace(strO,"5","Տ",-1)
	strO = strings.Replace(strO,"6","ճ",-1)
	strO = strings.Replace(strO,"7","Դ",-1)
	strO = strings.Replace(strO,"8","Ց",-1)
	strO = strings.Replace(strO,"9","գ",-1)
	strO = strings.Replace(strO,"A","𝔄",-1)
	strO = strings.Replace(strO,"B","𝔅",-1)
	strO = strings.Replace(strO,"C","ℭ",-1)
	strO = strings.Replace(strO,"D","𝔇",-1)
	strO = strings.Replace(strO,"E","𝔈",-1)
	strO = strings.Replace(strO,"F","𝔉",-1)
	strO = strings.Replace(strO,"G","𝔊",-1)
	strO = strings.Replace(strO,"H","ℌ",-1)
	strO = strings.Replace(strO,"I","ℑ",-1)
	strO = strings.Replace(strO,"J","𝔍",-1)
	strO = strings.Replace(strO,"K","𝔎",-1)
	strO = strings.Replace(strO,"L","𝔏",-1)
	strO = strings.Replace(strO,"M","𝔐",-1)
	strO = strings.Replace(strO,"N","𝔑",-1)
	strO = strings.Replace(strO,"O","𝔒",-1)
	strO = strings.Replace(strO,"P","𝔓",-1)
	strO = strings.Replace(strO,"Q","𝔔",-1)
	strO = strings.Replace(strO,"R","ℜ",-1)
	strO = strings.Replace(strO,"S","𝔖",-1)
	strO = strings.Replace(strO,"T","𝔗",-1)
	strO = strings.Replace(strO,"U","𝔘",-1)
	strO = strings.Replace(strO,"V","𝔙",-1)
	strO = strings.Replace(strO,"W","𝔚",-1)
	strO = strings.Replace(strO,"X","𝔛",-1)
	strO = strings.Replace(strO,"Y","𝔜",-1)
	strO = strings.Replace(strO,"Z","ℨ",-1)
	strO = strings.Replace(strO,"a","𝔞",-1)
	strO = strings.Replace(strO,"b","𝔟",-1)
	strO = strings.Replace(strO,"c","𝔠",-1)
	strO = strings.Replace(strO,"d","𝔡",-1)
	strO = strings.Replace(strO,"e","𝔢",-1)
	strO = strings.Replace(strO,"f","𝔣",-1)
	strO = strings.Replace(strO,"g","𝔤",-1)
	strO = strings.Replace(strO,"h","𝔥",-1)
	strO = strings.Replace(strO,"i","𝔦",-1)
	strO = strings.Replace(strO,"j","𝔧",-1)
	strO = strings.Replace(strO,"k","𝔨",-1)
	strO = strings.Replace(strO,"l","𝔩",-1)
	strO = strings.Replace(strO,"m","𝔪",-1)
	strO = strings.Replace(strO,"n","𝔫",-1)
	strO = strings.Replace(strO,"o","𝔬",-1)
	strO = strings.Replace(strO,"p","𝔭",-1)
	strO = strings.Replace(strO,"q","𝔮",-1)
	strO = strings.Replace(strO,"r","𝔯",-1)
	strO = strings.Replace(strO,"s","𝔰",-1)
	strO = strings.Replace(strO,"t","𝔱",-1)
	strO = strings.Replace(strO,"u","𝔲",-1)
	strO = strings.Replace(strO,"v","𝔳",-1)
	strO = strings.Replace(strO,"w","𝔴",-1)
	strO = strings.Replace(strO,"x","𝔵",-1)
	strO = strings.Replace(strO,"y","𝔶",-1)
	strO = strings.Replace(strO,"z","𝔷",-1)
	return strO
}