package c_CoolText__Wiggle_Arms

import "strings"

const Name = "Wiggle Arms"
const NameSanitized = "Wiggle_Arms"
const NameLoweredSanitized = "wiggle_arms"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","0",-1)
	strO = strings.Replace(strO,"1","1",-1)
	strO = strings.Replace(strO,"2","2",-1)
	strO = strings.Replace(strO,"3","3",-1)
	strO = strings.Replace(strO,"4","4",-1)
	strO = strings.Replace(strO,"5","5",-1)
	strO = strings.Replace(strO,"6","6",-1)
	strO = strings.Replace(strO,"7","7",-1)
	strO = strings.Replace(strO,"8","8",-1)
	strO = strings.Replace(strO,"9","9",-1)
	strO = strings.Replace(strO,"A","ᗩ",-1)
	strO = strings.Replace(strO,"B","ᙖ",-1)
	strO = strings.Replace(strO,"C","ᙅ",-1)
	strO = strings.Replace(strO,"D","ᗪ",-1)
	strO = strings.Replace(strO,"E","ᙓ",-1)
	strO = strings.Replace(strO,"F","ᖴ",-1)
	strO = strings.Replace(strO,"G","ᘜ",-1)
	strO = strings.Replace(strO,"H","ᕼ",-1)
	strO = strings.Replace(strO,"I","I",-1)
	strO = strings.Replace(strO,"J","ᒍ",-1)
	strO = strings.Replace(strO,"K","K",-1)
	strO = strings.Replace(strO,"L","ᒪ",-1)
	strO = strings.Replace(strO,"M","ᙏ",-1)
	strO = strings.Replace(strO,"N","ᑎ",-1)
	strO = strings.Replace(strO,"O","O",-1)
	strO = strings.Replace(strO,"P","ᑭ",-1)
	strO = strings.Replace(strO,"Q","ᑫ",-1)
	strO = strings.Replace(strO,"R","ᖇ",-1)
	strO = strings.Replace(strO,"S","S",-1)
	strO = strings.Replace(strO,"T","T",-1)
	strO = strings.Replace(strO,"U","ᙀ",-1)
	strO = strings.Replace(strO,"V","ᐯ",-1)
	strO = strings.Replace(strO,"W","ᙎ",-1)
	strO = strings.Replace(strO,"X","᙭",-1)
	strO = strings.Replace(strO,"Y","Y",-1)
	strO = strings.Replace(strO,"Z","ᘔ",-1)
	strO = strings.Replace(strO,"a","ᗩ",-1)
	strO = strings.Replace(strO,"b","ᙖ",-1)
	strO = strings.Replace(strO,"c","ᙅ",-1)
	strO = strings.Replace(strO,"d","ᗪ",-1)
	strO = strings.Replace(strO,"e","ᙓ",-1)
	strO = strings.Replace(strO,"f","ᖴ",-1)
	strO = strings.Replace(strO,"g","ᘜ",-1)
	strO = strings.Replace(strO,"h","ᕼ",-1)
	strO = strings.Replace(strO,"i","I",-1)
	strO = strings.Replace(strO,"j","ᒍ",-1)
	strO = strings.Replace(strO,"k","K",-1)
	strO = strings.Replace(strO,"l","ᒪ",-1)
	strO = strings.Replace(strO,"m","ᙏ",-1)
	strO = strings.Replace(strO,"n","ᑎ",-1)
	strO = strings.Replace(strO,"o","O",-1)
	strO = strings.Replace(strO,"p","ᑭ",-1)
	strO = strings.Replace(strO,"q","ᑫ",-1)
	strO = strings.Replace(strO,"r","ᖇ",-1)
	strO = strings.Replace(strO,"s","S",-1)
	strO = strings.Replace(strO,"t","T",-1)
	strO = strings.Replace(strO,"u","ᙀ",-1)
	strO = strings.Replace(strO,"v","ᐯ",-1)
	strO = strings.Replace(strO,"w","ᙎ",-1)
	strO = strings.Replace(strO,"x","᙭",-1)
	strO = strings.Replace(strO,"y","Y",-1)
	strO = strings.Replace(strO,"z","ᘔ",-1)
	return strO
}