package c_CoolText__Wasai

import "strings"

const Name = "Wasai"
const NameSanitized = "Wasai"
const NameLoweredSanitized = "wasai"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","0",-1)
	strO = strings.Replace(strO,"1","1",-1)
	strO = strings.Replace(strO,"2","2",-1)
	strO = strings.Replace(strO,"3","3",-1)
	strO = strings.Replace(strO,"4","4",-1)
	strO = strings.Replace(strO,"5","5",-1)
	strO = strings.Replace(strO,"6","6",-1)
	strO = strings.Replace(strO,"7","7",-1)
	strO = strings.Replace(strO,"8","8",-1)
	strO = strings.Replace(strO,"9","9",-1)
	strO = strings.Replace(strO,"A","卂",-1)
	strO = strings.Replace(strO,"B","乃",-1)
	strO = strings.Replace(strO,"C","匚",-1)
	strO = strings.Replace(strO,"D","ᗪ",-1)
	strO = strings.Replace(strO,"E","乇",-1)
	strO = strings.Replace(strO,"F","千",-1)
	strO = strings.Replace(strO,"G","Ꮆ",-1)
	strO = strings.Replace(strO,"H","卄",-1)
	strO = strings.Replace(strO,"I","丨",-1)
	strO = strings.Replace(strO,"J","ﾌ",-1)
	strO = strings.Replace(strO,"K","Ҝ",-1)
	strO = strings.Replace(strO,"L","ㄥ",-1)
	strO = strings.Replace(strO,"M","爪",-1)
	strO = strings.Replace(strO,"N","几",-1)
	strO = strings.Replace(strO,"O","ㄖ",-1)
	strO = strings.Replace(strO,"P","卩",-1)
	strO = strings.Replace(strO,"Q","Ɋ",-1)
	strO = strings.Replace(strO,"R","尺",-1)
	strO = strings.Replace(strO,"S","丂",-1)
	strO = strings.Replace(strO,"T","ㄒ",-1)
	strO = strings.Replace(strO,"U","ㄩ",-1)
	strO = strings.Replace(strO,"V","ᐯ",-1)
	strO = strings.Replace(strO,"W","山",-1)
	strO = strings.Replace(strO,"X","乂",-1)
	strO = strings.Replace(strO,"Y","ㄚ",-1)
	strO = strings.Replace(strO,"Z","乙",-1)
	strO = strings.Replace(strO,"a","卂",-1)
	strO = strings.Replace(strO,"b","乃",-1)
	strO = strings.Replace(strO,"c","匚",-1)
	strO = strings.Replace(strO,"d","ᗪ",-1)
	strO = strings.Replace(strO,"e","乇",-1)
	strO = strings.Replace(strO,"f","千",-1)
	strO = strings.Replace(strO,"g","Ꮆ",-1)
	strO = strings.Replace(strO,"h","卄",-1)
	strO = strings.Replace(strO,"i","丨",-1)
	strO = strings.Replace(strO,"j","ﾌ",-1)
	strO = strings.Replace(strO,"k","Ҝ",-1)
	strO = strings.Replace(strO,"l","ㄥ",-1)
	strO = strings.Replace(strO,"m","爪",-1)
	strO = strings.Replace(strO,"n","几",-1)
	strO = strings.Replace(strO,"o","ㄖ",-1)
	strO = strings.Replace(strO,"p","卩",-1)
	strO = strings.Replace(strO,"q","Ɋ",-1)
	strO = strings.Replace(strO,"r","尺",-1)
	strO = strings.Replace(strO,"s","丂",-1)
	strO = strings.Replace(strO,"t","ㄒ",-1)
	strO = strings.Replace(strO,"u","ㄩ",-1)
	strO = strings.Replace(strO,"v","ᐯ",-1)
	strO = strings.Replace(strO,"w","山",-1)
	strO = strings.Replace(strO,"x","乂",-1)
	strO = strings.Replace(strO,"y","ㄚ",-1)
	strO = strings.Replace(strO,"z","乙",-1)
	return strO
}