package c_CoolText__Notes

import "strings"

const Name = "Notes"
const NameSanitized = "Notes"
const NameLoweredSanitized = "notes"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","0",-1)
	strO = strings.Replace(strO,"1","1",-1)
	strO = strings.Replace(strO,"2","2",-1)
	strO = strings.Replace(strO,"3","3",-1)
	strO = strings.Replace(strO,"4","4",-1)
	strO = strings.Replace(strO,"5","5",-1)
	strO = strings.Replace(strO,"6","6",-1)
	strO = strings.Replace(strO,"7","7",-1)
	strO = strings.Replace(strO,"8","8",-1)
	strO = strings.Replace(strO,"9","9",-1)
	strO = strings.Replace(strO,"A","A",-1)
	strO = strings.Replace(strO,"B","B",-1)
	strO = strings.Replace(strO,"C","C",-1)
	strO = strings.Replace(strO,"D","D",-1)
	strO = strings.Replace(strO,"E","E",-1)
	strO = strings.Replace(strO,"F","F",-1)
	strO = strings.Replace(strO,"G","G",-1)
	strO = strings.Replace(strO,"H","H",-1)
	strO = strings.Replace(strO,"I","I",-1)
	strO = strings.Replace(strO,"J","J",-1)
	strO = strings.Replace(strO,"K","K",-1)
	strO = strings.Replace(strO,"L","L",-1)
	strO = strings.Replace(strO,"M","M",-1)
	strO = strings.Replace(strO,"N","N",-1)
	strO = strings.Replace(strO,"O","O",-1)
	strO = strings.Replace(strO,"P","P",-1)
	strO = strings.Replace(strO,"Q","Q",-1)
	strO = strings.Replace(strO,"R","R",-1)
	strO = strings.Replace(strO,"S","S",-1)
	strO = strings.Replace(strO,"T","T",-1)
	strO = strings.Replace(strO,"U","U",-1)
	strO = strings.Replace(strO,"V","V",-1)
	strO = strings.Replace(strO,"W","W",-1)
	strO = strings.Replace(strO,"X","X",-1)
	strO = strings.Replace(strO,"Y","Y",-1)
	strO = strings.Replace(strO,"Z","Z",-1)
	strO = strings.Replace(strO,"a","ᾰ",-1)
	strO = strings.Replace(strO,"b","♭",-1)
	strO = strings.Replace(strO,"c","ḉ",-1)
	strO = strings.Replace(strO,"d","ᖱ",-1)
	strO = strings.Replace(strO,"e","ḙ",-1)
	strO = strings.Replace(strO,"f","ḟ",-1)
	strO = strings.Replace(strO,"g","❡",-1)
	strO = strings.Replace(strO,"h","ℏ",-1)
	strO = strings.Replace(strO,"i","!",-1)
	strO = strings.Replace(strO,"j","♩",-1)
	strO = strings.Replace(strO,"k","к",-1)
	strO = strings.Replace(strO,"l","ℓ",-1)
	strO = strings.Replace(strO,"m","Պ",-1)
	strO = strings.Replace(strO,"n","ℵ",-1)
	strO = strings.Replace(strO,"o","✺",-1)
	strO = strings.Replace(strO,"p","℘",-1)
	strO = strings.Replace(strO,"q","ǭ",-1)
	strO = strings.Replace(strO,"r","Ի",-1)
	strO = strings.Replace(strO,"s","ṧ",-1)
	strO = strings.Replace(strO,"t","т",-1)
	strO = strings.Replace(strO,"u","ṳ",-1)
	strO = strings.Replace(strO,"v","ṽ",-1)
	strO = strings.Replace(strO,"w","ω",-1)
	strO = strings.Replace(strO,"x","✘",-1)
	strO = strings.Replace(strO,"y","⑂",-1)
	strO = strings.Replace(strO,"z","ℨ",-1)
	return strO
}