package c_CoolText__Serif_Bold

import "strings"

const Name = "Serif Bold"
const NameSanitized = "Serif_Bold"
const NameLoweredSanitized = "serif_bold"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","𝟎",-1)
	strO = strings.Replace(strO,"1","𝟏",-1)
	strO = strings.Replace(strO,"2","𝟐",-1)
	strO = strings.Replace(strO,"3","𝟑",-1)
	strO = strings.Replace(strO,"4","𝟒",-1)
	strO = strings.Replace(strO,"5","𝟓",-1)
	strO = strings.Replace(strO,"6","𝟔",-1)
	strO = strings.Replace(strO,"7","𝟕",-1)
	strO = strings.Replace(strO,"8","𝟖",-1)
	strO = strings.Replace(strO,"9","𝟗",-1)
	strO = strings.Replace(strO,"A","𝐀",-1)
	strO = strings.Replace(strO,"B","𝐁",-1)
	strO = strings.Replace(strO,"C","𝐂",-1)
	strO = strings.Replace(strO,"D","𝐃",-1)
	strO = strings.Replace(strO,"E","𝐄",-1)
	strO = strings.Replace(strO,"F","𝐅",-1)
	strO = strings.Replace(strO,"G","𝐆",-1)
	strO = strings.Replace(strO,"H","𝐇",-1)
	strO = strings.Replace(strO,"I","𝐈",-1)
	strO = strings.Replace(strO,"J","𝐉",-1)
	strO = strings.Replace(strO,"K","𝐊",-1)
	strO = strings.Replace(strO,"L","𝐋",-1)
	strO = strings.Replace(strO,"M","𝐌",-1)
	strO = strings.Replace(strO,"N","𝐍",-1)
	strO = strings.Replace(strO,"O","𝐎",-1)
	strO = strings.Replace(strO,"P","𝐏",-1)
	strO = strings.Replace(strO,"Q","𝐐",-1)
	strO = strings.Replace(strO,"R","𝐑",-1)
	strO = strings.Replace(strO,"S","𝐒",-1)
	strO = strings.Replace(strO,"T","𝐓",-1)
	strO = strings.Replace(strO,"U","𝐔",-1)
	strO = strings.Replace(strO,"V","𝐕",-1)
	strO = strings.Replace(strO,"W","𝐖",-1)
	strO = strings.Replace(strO,"X","𝐗",-1)
	strO = strings.Replace(strO,"Y","𝐘",-1)
	strO = strings.Replace(strO,"Z","𝐙",-1)
	strO = strings.Replace(strO,"a","𝐚",-1)
	strO = strings.Replace(strO,"b","𝐛",-1)
	strO = strings.Replace(strO,"c","𝐜",-1)
	strO = strings.Replace(strO,"d","𝐝",-1)
	strO = strings.Replace(strO,"e","𝐞",-1)
	strO = strings.Replace(strO,"f","𝐟",-1)
	strO = strings.Replace(strO,"g","𝐠",-1)
	strO = strings.Replace(strO,"h","𝐡",-1)
	strO = strings.Replace(strO,"i","𝐢",-1)
	strO = strings.Replace(strO,"j","𝐣",-1)
	strO = strings.Replace(strO,"k","𝐤",-1)
	strO = strings.Replace(strO,"l","𝐥",-1)
	strO = strings.Replace(strO,"m","𝐦",-1)
	strO = strings.Replace(strO,"n","𝐧",-1)
	strO = strings.Replace(strO,"o","𝐨",-1)
	strO = strings.Replace(strO,"p","𝐩",-1)
	strO = strings.Replace(strO,"q","𝐪",-1)
	strO = strings.Replace(strO,"r","𝐫",-1)
	strO = strings.Replace(strO,"s","𝐬",-1)
	strO = strings.Replace(strO,"t","𝐭",-1)
	strO = strings.Replace(strO,"u","𝐮",-1)
	strO = strings.Replace(strO,"v","𝐯",-1)
	strO = strings.Replace(strO,"w","𝐰",-1)
	strO = strings.Replace(strO,"x","𝐱",-1)
	strO = strings.Replace(strO,"y","𝐲",-1)
	strO = strings.Replace(strO,"z","𝐳",-1)
	return strO
}