package c_CoolText__Short_Caps

import "strings"

const Name = "Short Caps"
const NameSanitized = "Short_Caps"
const NameLoweredSanitized = "short_caps"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","0",-1)
	strO = strings.Replace(strO,"1","1",-1)
	strO = strings.Replace(strO,"2","2",-1)
	strO = strings.Replace(strO,"3","3",-1)
	strO = strings.Replace(strO,"4","4",-1)
	strO = strings.Replace(strO,"5","5",-1)
	strO = strings.Replace(strO,"6","6",-1)
	strO = strings.Replace(strO,"7","7",-1)
	strO = strings.Replace(strO,"8","8",-1)
	strO = strings.Replace(strO,"9","9",-1)
	strO = strings.Replace(strO,"A","A",-1)
	strO = strings.Replace(strO,"B","B",-1)
	strO = strings.Replace(strO,"C","C",-1)
	strO = strings.Replace(strO,"D","D",-1)
	strO = strings.Replace(strO,"E","E",-1)
	strO = strings.Replace(strO,"F","F",-1)
	strO = strings.Replace(strO,"G","G",-1)
	strO = strings.Replace(strO,"H","H",-1)
	strO = strings.Replace(strO,"I","I",-1)
	strO = strings.Replace(strO,"J","J",-1)
	strO = strings.Replace(strO,"K","K",-1)
	strO = strings.Replace(strO,"L","L",-1)
	strO = strings.Replace(strO,"M","M",-1)
	strO = strings.Replace(strO,"N","N",-1)
	strO = strings.Replace(strO,"O","O",-1)
	strO = strings.Replace(strO,"P","P",-1)
	strO = strings.Replace(strO,"Q","Q",-1)
	strO = strings.Replace(strO,"R","R",-1)
	strO = strings.Replace(strO,"S","S",-1)
	strO = strings.Replace(strO,"T","T",-1)
	strO = strings.Replace(strO,"U","U",-1)
	strO = strings.Replace(strO,"V","V",-1)
	strO = strings.Replace(strO,"W","W",-1)
	strO = strings.Replace(strO,"X","X",-1)
	strO = strings.Replace(strO,"Y","Y",-1)
	strO = strings.Replace(strO,"Z","Z",-1)
	strO = strings.Replace(strO,"a","α",-1)
	strO = strings.Replace(strO,"b","в",-1)
	strO = strings.Replace(strO,"c","c",-1)
	strO = strings.Replace(strO,"d","d",-1)
	strO = strings.Replace(strO,"e","e",-1)
	strO = strings.Replace(strO,"f","ғ",-1)
	strO = strings.Replace(strO,"g","ɢ",-1)
	strO = strings.Replace(strO,"h","н",-1)
	strO = strings.Replace(strO,"i","ι",-1)
	strO = strings.Replace(strO,"j","j",-1)
	strO = strings.Replace(strO,"k","ĸ",-1)
	strO = strings.Replace(strO,"l","l",-1)
	strO = strings.Replace(strO,"m","м",-1)
	strO = strings.Replace(strO,"n","ɴ",-1)
	strO = strings.Replace(strO,"o","o",-1)
	strO = strings.Replace(strO,"p","p",-1)
	strO = strings.Replace(strO,"q","q",-1)
	strO = strings.Replace(strO,"r","r",-1)
	strO = strings.Replace(strO,"s","ѕ",-1)
	strO = strings.Replace(strO,"t","т",-1)
	strO = strings.Replace(strO,"u","υ",-1)
	strO = strings.Replace(strO,"v","v",-1)
	strO = strings.Replace(strO,"w","w",-1)
	strO = strings.Replace(strO,"x","х",-1)
	strO = strings.Replace(strO,"y","y",-1)
	strO = strings.Replace(strO,"z","z",-1)
	return strO
}