package c_CoolText__Kings_Landing

import "strings"

const Name = "King's Landing"
const NameSanitized = "Kings_Landing"
const NameLoweredSanitized = "kings_landing"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","𝟘",-1)
	strO = strings.Replace(strO,"1","𝟙",-1)
	strO = strings.Replace(strO,"2","𝟚",-1)
	strO = strings.Replace(strO,"3","𝟛",-1)
	strO = strings.Replace(strO,"4","𝟜",-1)
	strO = strings.Replace(strO,"5","𝟝",-1)
	strO = strings.Replace(strO,"6","𝟞",-1)
	strO = strings.Replace(strO,"7","𝟟",-1)
	strO = strings.Replace(strO,"8","𝟠",-1)
	strO = strings.Replace(strO,"9","𝟡",-1)
	strO = strings.Replace(strO,"A","𝔸",-1)
	strO = strings.Replace(strO,"B","𝔹",-1)
	strO = strings.Replace(strO,"C","ℂ",-1)
	strO = strings.Replace(strO,"D","𝔻",-1)
	strO = strings.Replace(strO,"E","𝔼",-1)
	strO = strings.Replace(strO,"F","𝔽",-1)
	strO = strings.Replace(strO,"G","𝔾",-1)
	strO = strings.Replace(strO,"H","ℍ",-1)
	strO = strings.Replace(strO,"I","𝕀",-1)
	strO = strings.Replace(strO,"J","𝕁",-1)
	strO = strings.Replace(strO,"K","𝕂",-1)
	strO = strings.Replace(strO,"L","𝕃",-1)
	strO = strings.Replace(strO,"M","𝕄",-1)
	strO = strings.Replace(strO,"N","ℕ",-1)
	strO = strings.Replace(strO,"O","𝕆",-1)
	strO = strings.Replace(strO,"P","ℙ",-1)
	strO = strings.Replace(strO,"Q","ℚ",-1)
	strO = strings.Replace(strO,"R","ℝ",-1)
	strO = strings.Replace(strO,"S","𝕊",-1)
	strO = strings.Replace(strO,"T","𝕋",-1)
	strO = strings.Replace(strO,"U","𝕌",-1)
	strO = strings.Replace(strO,"V","𝕍",-1)
	strO = strings.Replace(strO,"W","𝕎",-1)
	strO = strings.Replace(strO,"X","𝕏",-1)
	strO = strings.Replace(strO,"Y","𝕐",-1)
	strO = strings.Replace(strO,"Z","ℤ",-1)
	strO = strings.Replace(strO,"a","𝕒",-1)
	strO = strings.Replace(strO,"b","𝕓",-1)
	strO = strings.Replace(strO,"c","𝕔",-1)
	strO = strings.Replace(strO,"d","𝕕",-1)
	strO = strings.Replace(strO,"e","𝕖",-1)
	strO = strings.Replace(strO,"f","𝕗",-1)
	strO = strings.Replace(strO,"g","𝕘",-1)
	strO = strings.Replace(strO,"h","𝕙",-1)
	strO = strings.Replace(strO,"i","𝕚",-1)
	strO = strings.Replace(strO,"j","𝕛",-1)
	strO = strings.Replace(strO,"k","𝕜",-1)
	strO = strings.Replace(strO,"l","𝕝",-1)
	strO = strings.Replace(strO,"m","𝕞",-1)
	strO = strings.Replace(strO,"n","𝕟",-1)
	strO = strings.Replace(strO,"o","𝕠",-1)
	strO = strings.Replace(strO,"p","𝕡",-1)
	strO = strings.Replace(strO,"q","𝕢",-1)
	strO = strings.Replace(strO,"r","𝕣",-1)
	strO = strings.Replace(strO,"s","𝕤",-1)
	strO = strings.Replace(strO,"t","𝕥",-1)
	strO = strings.Replace(strO,"u","𝕦",-1)
	strO = strings.Replace(strO,"v","𝕧",-1)
	strO = strings.Replace(strO,"w","𝕨",-1)
	strO = strings.Replace(strO,"x","𝕩",-1)
	strO = strings.Replace(strO,"y","𝕪",-1)
	strO = strings.Replace(strO,"z","𝕫",-1)
	return strO
}