package c_CoolText__Top_Hat

import "strings"

const Name = "Top Hat"
const NameSanitized = "Top_Hat"
const NameLoweredSanitized = "top_hat"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","0̲̅",-1)
	strO = strings.Replace(strO,"1","1̲̅",-1)
	strO = strings.Replace(strO,"2","2̲̅",-1)
	strO = strings.Replace(strO,"3","3̲̅",-1)
	strO = strings.Replace(strO,"4","4̲̅",-1)
	strO = strings.Replace(strO,"5","5̲̅",-1)
	strO = strings.Replace(strO,"6","6̲̅",-1)
	strO = strings.Replace(strO,"7","7̲̅",-1)
	strO = strings.Replace(strO,"8","8̲̅",-1)
	strO = strings.Replace(strO,"9","9̲̅",-1)
	strO = strings.Replace(strO,"A","𝑨̲̅",-1)
	strO = strings.Replace(strO,"B","𝑩̲̅",-1)
	strO = strings.Replace(strO,"C","𝑪̲̅",-1)
	strO = strings.Replace(strO,"D","𝑫̲̅",-1)
	strO = strings.Replace(strO,"E","𝑬̲̅",-1)
	strO = strings.Replace(strO,"F","𝑭̲̅",-1)
	strO = strings.Replace(strO,"G","𝑮̲̅",-1)
	strO = strings.Replace(strO,"H","𝑯̲̅",-1)
	strO = strings.Replace(strO,"I","𝑰̲̅",-1)
	strO = strings.Replace(strO,"J","𝑱̲̅",-1)
	strO = strings.Replace(strO,"K","𝑲̲̅",-1)
	strO = strings.Replace(strO,"L","𝑳̲̅",-1)
	strO = strings.Replace(strO,"M","𝑴̲̅",-1)
	strO = strings.Replace(strO,"N","𝑵̲̅",-1)
	strO = strings.Replace(strO,"O","𝑶̲̅",-1)
	strO = strings.Replace(strO,"P","𝑷̲̅",-1)
	strO = strings.Replace(strO,"Q","𝑸̲̅",-1)
	strO = strings.Replace(strO,"R","𝑹̲̅",-1)
	strO = strings.Replace(strO,"S","𝑺̲̅",-1)
	strO = strings.Replace(strO,"T","𝑻̲̅",-1)
	strO = strings.Replace(strO,"U","𝑼̲̅",-1)
	strO = strings.Replace(strO,"V","𝑽̲̅",-1)
	strO = strings.Replace(strO,"W","𝑾̲̅",-1)
	strO = strings.Replace(strO,"X","𝑿̲̅",-1)
	strO = strings.Replace(strO,"Y","𝒀̲̅",-1)
	strO = strings.Replace(strO,"Z","𝒁̲̅",-1)
	strO = strings.Replace(strO,"a","𝒂̲̅",-1)
	strO = strings.Replace(strO,"b","𝒃̲̅",-1)
	strO = strings.Replace(strO,"c","𝒄̲̅",-1)
	strO = strings.Replace(strO,"d","𝒅̲̅",-1)
	strO = strings.Replace(strO,"e","𝒆̲̅",-1)
	strO = strings.Replace(strO,"f","𝒇̲̅",-1)
	strO = strings.Replace(strO,"g","𝒈̲̅",-1)
	strO = strings.Replace(strO,"h","𝒉̲̅",-1)
	strO = strings.Replace(strO,"i","𝒊̲̅",-1)
	strO = strings.Replace(strO,"j","𝒋̲̅",-1)
	strO = strings.Replace(strO,"k","𝒌̲̅",-1)
	strO = strings.Replace(strO,"l","𝒍̲̅",-1)
	strO = strings.Replace(strO,"m","𝒎̲̅",-1)
	strO = strings.Replace(strO,"n","𝒏̲̅",-1)
	strO = strings.Replace(strO,"o","𝒐̲̅",-1)
	strO = strings.Replace(strO,"p","𝒑̲̅",-1)
	strO = strings.Replace(strO,"q","𝒒̲̅",-1)
	strO = strings.Replace(strO,"r","𝒓̲̅",-1)
	strO = strings.Replace(strO,"s","𝒔̲̅",-1)
	strO = strings.Replace(strO,"t","𝒕̲̅",-1)
	strO = strings.Replace(strO,"u","𝒖̲̅",-1)
	strO = strings.Replace(strO,"v","𝒗̲̅",-1)
	strO = strings.Replace(strO,"w","𝒘̲̅",-1)
	strO = strings.Replace(strO,"x","𝒙̲̅",-1)
	strO = strings.Replace(strO,"y","𝒚̲̅",-1)
	strO = strings.Replace(strO,"z","𝒛̲̅",-1)
	return strO
}