package c_CoolText__Italic

import "strings"

const Name = "Italic"
const NameSanitized = "Italic"
const NameLoweredSanitized = "italic"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","0",-1)
	strO = strings.Replace(strO,"1","1",-1)
	strO = strings.Replace(strO,"2","2",-1)
	strO = strings.Replace(strO,"3","3",-1)
	strO = strings.Replace(strO,"4","4",-1)
	strO = strings.Replace(strO,"5","5",-1)
	strO = strings.Replace(strO,"6","6",-1)
	strO = strings.Replace(strO,"7","7",-1)
	strO = strings.Replace(strO,"8","8",-1)
	strO = strings.Replace(strO,"9","9",-1)
	strO = strings.Replace(strO,"A","𝘈",-1)
	strO = strings.Replace(strO,"B","𝘉",-1)
	strO = strings.Replace(strO,"C","𝘊",-1)
	strO = strings.Replace(strO,"D","𝘋",-1)
	strO = strings.Replace(strO,"E","𝘌",-1)
	strO = strings.Replace(strO,"F","𝘍",-1)
	strO = strings.Replace(strO,"G","𝘎",-1)
	strO = strings.Replace(strO,"H","𝘏",-1)
	strO = strings.Replace(strO,"I","𝘐",-1)
	strO = strings.Replace(strO,"J","𝘑",-1)
	strO = strings.Replace(strO,"K","𝘒",-1)
	strO = strings.Replace(strO,"L","𝘓",-1)
	strO = strings.Replace(strO,"M","𝘔",-1)
	strO = strings.Replace(strO,"N","𝘕",-1)
	strO = strings.Replace(strO,"O","𝘖",-1)
	strO = strings.Replace(strO,"P","𝘗",-1)
	strO = strings.Replace(strO,"Q","𝘘",-1)
	strO = strings.Replace(strO,"R","𝘙",-1)
	strO = strings.Replace(strO,"S","𝘚",-1)
	strO = strings.Replace(strO,"T","𝘛",-1)
	strO = strings.Replace(strO,"U","𝘜",-1)
	strO = strings.Replace(strO,"V","𝘝",-1)
	strO = strings.Replace(strO,"W","𝘞",-1)
	strO = strings.Replace(strO,"X","𝘟",-1)
	strO = strings.Replace(strO,"Y","𝘠",-1)
	strO = strings.Replace(strO,"Z","𝘡",-1)
	strO = strings.Replace(strO,"a","𝘢",-1)
	strO = strings.Replace(strO,"b","𝘣",-1)
	strO = strings.Replace(strO,"c","𝘤",-1)
	strO = strings.Replace(strO,"d","𝘥",-1)
	strO = strings.Replace(strO,"e","𝘦",-1)
	strO = strings.Replace(strO,"f","𝘧",-1)
	strO = strings.Replace(strO,"g","𝘨",-1)
	strO = strings.Replace(strO,"h","𝘩",-1)
	strO = strings.Replace(strO,"i","𝘪",-1)
	strO = strings.Replace(strO,"j","𝘫",-1)
	strO = strings.Replace(strO,"k","𝘬",-1)
	strO = strings.Replace(strO,"l","𝘭",-1)
	strO = strings.Replace(strO,"m","𝘮",-1)
	strO = strings.Replace(strO,"n","𝘯",-1)
	strO = strings.Replace(strO,"o","𝘰",-1)
	strO = strings.Replace(strO,"p","𝘱",-1)
	strO = strings.Replace(strO,"q","𝘲",-1)
	strO = strings.Replace(strO,"r","𝘳",-1)
	strO = strings.Replace(strO,"s","𝘴",-1)
	strO = strings.Replace(strO,"t","𝘵",-1)
	strO = strings.Replace(strO,"u","𝘶",-1)
	strO = strings.Replace(strO,"v","𝘷",-1)
	strO = strings.Replace(strO,"w","𝘸",-1)
	strO = strings.Replace(strO,"x","𝘹",-1)
	strO = strings.Replace(strO,"y","𝘺",-1)
	strO = strings.Replace(strO,"z","𝘻",-1)
	return strO
}