package c_CoolText__Strikethrough

import "strings"

const Name = "Strikethrough"
const NameSanitized = "Strikethrough"
const NameLoweredSanitized = "strikethrough"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","0̶",-1)
	strO = strings.Replace(strO,"1","1̶",-1)
	strO = strings.Replace(strO,"2","2̶",-1)
	strO = strings.Replace(strO,"3","3̶",-1)
	strO = strings.Replace(strO,"4","4̶",-1)
	strO = strings.Replace(strO,"5","5̶",-1)
	strO = strings.Replace(strO,"6","6̶",-1)
	strO = strings.Replace(strO,"7","7̶",-1)
	strO = strings.Replace(strO,"8","8̶",-1)
	strO = strings.Replace(strO,"9","9̶",-1)
	strO = strings.Replace(strO,"A","A̶",-1)
	strO = strings.Replace(strO,"B","B̶",-1)
	strO = strings.Replace(strO,"C","C̶",-1)
	strO = strings.Replace(strO,"D","D̶",-1)
	strO = strings.Replace(strO,"E","E̶",-1)
	strO = strings.Replace(strO,"F","F̶",-1)
	strO = strings.Replace(strO,"G","G̶",-1)
	strO = strings.Replace(strO,"H","H̶",-1)
	strO = strings.Replace(strO,"I","I̶",-1)
	strO = strings.Replace(strO,"J","J̶",-1)
	strO = strings.Replace(strO,"K","K̶",-1)
	strO = strings.Replace(strO,"L","L̶",-1)
	strO = strings.Replace(strO,"M","M̶",-1)
	strO = strings.Replace(strO,"N","N̶",-1)
	strO = strings.Replace(strO,"O","O̶",-1)
	strO = strings.Replace(strO,"P","P̶",-1)
	strO = strings.Replace(strO,"Q","Q̶",-1)
	strO = strings.Replace(strO,"R","R̶",-1)
	strO = strings.Replace(strO,"S","S̶",-1)
	strO = strings.Replace(strO,"T","T̶",-1)
	strO = strings.Replace(strO,"U","U̶",-1)
	strO = strings.Replace(strO,"V","V̶",-1)
	strO = strings.Replace(strO,"W","W̶",-1)
	strO = strings.Replace(strO,"X","X̶",-1)
	strO = strings.Replace(strO,"Y","Y̶",-1)
	strO = strings.Replace(strO,"Z","Z̶",-1)
	strO = strings.Replace(strO,"a","a̶",-1)
	strO = strings.Replace(strO,"b","b̶",-1)
	strO = strings.Replace(strO,"c","c̶",-1)
	strO = strings.Replace(strO,"d","d̶",-1)
	strO = strings.Replace(strO,"e","e̶",-1)
	strO = strings.Replace(strO,"f","f̶",-1)
	strO = strings.Replace(strO,"g","g̶",-1)
	strO = strings.Replace(strO,"h","h̶",-1)
	strO = strings.Replace(strO,"i","i̶",-1)
	strO = strings.Replace(strO,"j","j̶",-1)
	strO = strings.Replace(strO,"k","k̶",-1)
	strO = strings.Replace(strO,"l","l̶",-1)
	strO = strings.Replace(strO,"m","m̶",-1)
	strO = strings.Replace(strO,"n","n̶",-1)
	strO = strings.Replace(strO,"o","o̶",-1)
	strO = strings.Replace(strO,"p","p̶",-1)
	strO = strings.Replace(strO,"q","q̶",-1)
	strO = strings.Replace(strO,"r","r̶",-1)
	strO = strings.Replace(strO,"s","s̶",-1)
	strO = strings.Replace(strO,"t","t̶",-1)
	strO = strings.Replace(strO,"u","u̶",-1)
	strO = strings.Replace(strO,"v","v̶",-1)
	strO = strings.Replace(strO,"w","w̶",-1)
	strO = strings.Replace(strO,"x","x̶",-1)
	strO = strings.Replace(strO,"y","y̶",-1)
	strO = strings.Replace(strO,"z","z̶",-1)
	return strO
}