package c_CoolText__Typewriter

import "strings"

const Name = "Typewriter"
const NameSanitized = "Typewriter"
const NameLoweredSanitized = "typewriter"

func Replace(str string) string {
	var strO string
	strO = strings.Replace(str,"0","𝟶",-1)
	strO = strings.Replace(strO,"1","𝟷",-1)
	strO = strings.Replace(strO,"2","𝟸",-1)
	strO = strings.Replace(strO,"3","𝟹",-1)
	strO = strings.Replace(strO,"4","𝟺",-1)
	strO = strings.Replace(strO,"5","𝟻",-1)
	strO = strings.Replace(strO,"6","𝟼",-1)
	strO = strings.Replace(strO,"7","𝟽",-1)
	strO = strings.Replace(strO,"8","𝟾",-1)
	strO = strings.Replace(strO,"9","𝟿",-1)
	strO = strings.Replace(strO,"A","𝙰",-1)
	strO = strings.Replace(strO,"B","𝙱",-1)
	strO = strings.Replace(strO,"C","𝙲",-1)
	strO = strings.Replace(strO,"D","𝙳",-1)
	strO = strings.Replace(strO,"E","𝙴",-1)
	strO = strings.Replace(strO,"F","𝙵",-1)
	strO = strings.Replace(strO,"G","𝙶",-1)
	strO = strings.Replace(strO,"H","𝙷",-1)
	strO = strings.Replace(strO,"I","𝙸",-1)
	strO = strings.Replace(strO,"J","𝙹",-1)
	strO = strings.Replace(strO,"K","𝙺",-1)
	strO = strings.Replace(strO,"L","𝙻",-1)
	strO = strings.Replace(strO,"M","𝙼",-1)
	strO = strings.Replace(strO,"N","𝙽",-1)
	strO = strings.Replace(strO,"O","𝙾",-1)
	strO = strings.Replace(strO,"P","𝙿",-1)
	strO = strings.Replace(strO,"Q","𝚀",-1)
	strO = strings.Replace(strO,"R","𝚁",-1)
	strO = strings.Replace(strO,"S","𝚂",-1)
	strO = strings.Replace(strO,"T","𝚃",-1)
	strO = strings.Replace(strO,"U","𝚄",-1)
	strO = strings.Replace(strO,"V","𝚅",-1)
	strO = strings.Replace(strO,"W","𝚆",-1)
	strO = strings.Replace(strO,"X","𝚇",-1)
	strO = strings.Replace(strO,"Y","𝚈",-1)
	strO = strings.Replace(strO,"Z","𝚉",-1)
	strO = strings.Replace(strO,"a","𝚊",-1)
	strO = strings.Replace(strO,"b","𝚋",-1)
	strO = strings.Replace(strO,"c","𝚌",-1)
	strO = strings.Replace(strO,"d","𝚍",-1)
	strO = strings.Replace(strO,"e","𝚎",-1)
	strO = strings.Replace(strO,"f","𝚏",-1)
	strO = strings.Replace(strO,"g","𝚐",-1)
	strO = strings.Replace(strO,"h","𝚑",-1)
	strO = strings.Replace(strO,"i","𝚒",-1)
	strO = strings.Replace(strO,"j","𝚓",-1)
	strO = strings.Replace(strO,"k","𝚔",-1)
	strO = strings.Replace(strO,"l","𝚕",-1)
	strO = strings.Replace(strO,"m","𝚖",-1)
	strO = strings.Replace(strO,"n","𝚗",-1)
	strO = strings.Replace(strO,"o","𝚘",-1)
	strO = strings.Replace(strO,"p","𝚙",-1)
	strO = strings.Replace(strO,"q","𝚚",-1)
	strO = strings.Replace(strO,"r","𝚛",-1)
	strO = strings.Replace(strO,"s","𝚜",-1)
	strO = strings.Replace(strO,"t","𝚝",-1)
	strO = strings.Replace(strO,"u","𝚞",-1)
	strO = strings.Replace(strO,"v","𝚟",-1)
	strO = strings.Replace(strO,"w","𝚠",-1)
	strO = strings.Replace(strO,"x","𝚡",-1)
	strO = strings.Replace(strO,"y","𝚢",-1)
	strO = strings.Replace(strO,"z","𝚣",-1)
	return strO
}